#!/bin/sh

exe=./dynamic-array

die() { test -n "$*" && echo "$*"; exit 1; } >&2

expect() {
	o=$(printf "$1" | $exe | md5sum)
	e=$(printf "$1" | md5sum)
	if test "$o" != "$e"; then
		die "Unexpected output for '$1'"
	fi
}

expect 'foo bar'
expect 'foo\000bar'
expect 'foo\377bar'

all=$(cat * 2> /dev/null | md5sum)
exp=$(cat * 2> /dev/null | $exe | md5sum)

if test "$all" != "$exp"; then
	die "Unexpected output on all files in $(pwd)"
fi
