#!/bin/sh

exe=./scanf-term
out=$($exe 2x^3 -2 -2x -2x^2 x | expand)
if test "$out" != '2x^3:   2,3
-2:     -2,0
-2x:    -2,1
-2x^2:  -2,2
x:      1,1'
then
	echo "Got unexpected: '$out'" >&2
	exit 1
fi
