#!/bin/bash
# Claude Code status line script
# Displays current working directory in the lower right

input=$(cat)

: << \EOF
# Sample input:
{
        "session_id": "4c1fa146-4766-4993-8c0b-8ddf35208c2b",
        "transcript_path": "/Users/wrp/.claude/projects/<snip>",
        "cwd": "/Users/wrp/github/wrp/examples/go/src",
        "model": {
                "id": "claude-sonnet-4-5-20250929",
                "display_name": "Sonnet 4.5"
        },
        "workspace": {
                "current_dir": "/Users/wrp/github/wrp/examples/go/src",
                "project_dir": "/Users/wrp/github/wrp/examples"
        },
        "version": "2.0.42",
        "output_style": {
                "name": "default"
        },
        "cost": {
                "total_cost_usd": 2.898200899999998,
                "total_duration_ms": 219119735,
                "total_api_duration_ms": 1656809,
                "total_lines_added": 13,
                "total_lines_removed": 15
        },
        "exceeds_200k_tokens": false
}
EOF

red=$(tput setaf 1)
green=$(tput setaf 2)
yellow=$(tput setaf 3)
blue=$(tput setaf 4)
cyan=$(tput setaf 6)

ws=$(echo "$input" | jq -r '.workspace.project_dir')
branch=$(git symbolic-ref --short HEAD || git rev-parse --short HEAD)
if test -n "$branch"; then
	branch="@$branch  --  ${cyan}$(git log -n1 --pretty=format:%s HEAD)"
fi


printf "${red}workspace:${yellow} ${ws##*/} ${green}cwd: ${yellow}$(pwd)$branch$(tput sgr0)\n"
