#!/bin/sh

test $# = 0 && set oncalls teams addons schedules

query() {
	curl -sS \
		-H 'Accept: application/vnd.pagerduty+json;version=2' \
		-H "Authorization: Token token=${PD_TOKEN:?}" \
		--data-urlencode 'limit=100' \
		-X GET \
		https://api.pagerduty.com/$1
}

for endpoint; do
	echo "*** $1 ***"
	query $endpoint | jq .
done

# See https://v2.developer.pagerduty.com/v2/page/api-reference
