#!/bin/sh

test $# = 0 && set oncalls teams addons schedules

query() {
	echo "*** $1 ***"
	curl -sS \
		-H 'Accept: application/vnd.pagerduty+json;version=2' \
		-H "Authorization: Token token=$(cat ~/secrets/pagerduty/key-a4t1)" \
		--data-urlencode 'limit=100' \
		-X GET \
		https://api.pagerduty.com/$1
}

for endpoint; do query $endpoint; done

# See https://v2.developer.pagerduty.com/v2/page/api-reference
