#!/bin/sh

test $# = 0 && set oncalls teams addons schedules incidents

query() {
	curl -sS \
		-H 'Accept: application/vnd.pagerduty+json;version=2' \
		-H "Authorization: Token token=${PD_TOKEN:?}" \
		--data-urlencode 'limit=100' \
		-X GET \
		https://api.pagerduty.com/$1
}

for endpoint; do
	query "$endpoint" | jq .
done

exit 0

See https://v2.developer.pagerduty.com/v2/page/api-reference

common quries (quoted for easy cut-n-paste):

escalation_policies
"incidents?team_ids[]=${PD_TEAM_ID}"
"incidents?team_ids[]=${PD_TEAM_ID}&sort_by=incident_number:DESC"
"incidents?team_ids[]=${PD_TEAM_ID}&sort_by=incident_number:DESC&offset=$((100 * i++))"
"incidents?sort_by=incident_number:DESC&offset=$((100 * i++))"
