#!/bin/sh

# List git-bug issues matched to their GitHub issue URL.

git-bug bug -f json | jq -r '
	sort_by(.metadata["github-url"] // "") |
	.[] |
	[
		.status,
		(.metadata["github-url"] // "" | split("/") | last // "(none)"),
		.human_id,
		.title
	] |
	"\(.[0])\t#\(.[1])\t\(.[2])\t\(.[3])"
' | column -t -s "$(printf '\t')"
