#!/usr/bin/env python

import pandas as pd

a = pd.read_csv('./data')
print("dataframe of ./data'")
print(a)
print("mean of height in ./data'")
print(a['height'].mean())
print("quantiles")
print(a['height'].quantile([.25,.5,.9]))

a = pd.DataFrame(
    {
        "A": [1.0, 2.0, 3, 4],
        "B": ['foo', 'bar', 'baz', 'qux'],
        "C": pd.Series(1, index=list(range(4)), dtype="float32"),
        "D": list((1, 2, 3, 5))
    }
)

# print(a)          # Print the entire data frame
last_row = a[-1:]   # create a new dataframe consisting of one row
b = a['A']          # create a new dataframe consisting of a single column

# create a dataframe in which the column matches an expression
greater = a['A'] > 2  # create a dataframe consisting of two columns: an integer index and true/false
g = a[greater]

# Select only two columns of the rows in which column A matches > 2
g = a.loc[greater, ['B', 'C']]


i = pd.DataFrame(  # Create dataframe indexed by integers
        [
            [1.0, 2.0, 3, 4],
            ['foo', 'bar', 'baz', 'qux'],
            pd.Series(1, index=list(range(4)), dtype="float32"),
            list((9, 2, 3, 5))
        ]
    )

z = i.iloc[[0,3],0]  # column 0 from rows 0 and 3
last = i.iloc[-1:]    # last row
first_col = i.iloc[:,0]
print('first col is:')
print(first_col)

# Get unique entries in a column
h = pd.DataFrame(
    {
        'foo': ['one', 'two', 'three', 'one'],
        'bar': [ 1, 2, 3, 1],
    }
)
print(h)
print('uniqe values of foo:')
for t in h.foo.unique():
    print(t)


# get mean of a grouped set
h = pd.DataFrame(
    {
        'v': [1, 2, 3, 4, 5, 6],
        'k': ['a', 'b', 'a', 'c', 'a', 'e'],
    }
)
print(h)
print('the mean of all values:')
print(h.groupby('k').mean())
