#!/usr/bin/env python

import sys
import pandas as pd

a = pd.DataFrame(
    {
        "A": [1.0, 2.0, 3, 4],
        "B": ['foo', 'bar', 'baz', 'qux'],
        "C": pd.Series(1, index=list(range(4)), dtype="float32"),
        "D": list((1, 2, 3, 5))
    }
)

# df[df['column-name'].str.contains('str')]
print( a[a['B'].str.contains('a')] )

# startswith f or endswith x
print( a[a['B'].str.startswith('f') | a['B'].str.endswith('x')])
