#!/usr/bin/env python

import pandas as pd


a = pd.DataFrame(
    {
        'k': ['aa', 'ab', 'ac', 'ba', 'bb', 'bc'],
        'v': [1.0,  1.5,  2,  3,   4,  5],
        'y': [1997] * 6,
    }
)

# Sum all rows where key starts with 'a'
rows = a.k.str.startswith('a')
print(a.loc[rows].sum()['v'])


# Sum all rows where key ends with 'c'
print(a.loc[a.k.str[-1] == 'c'].sum()['v'])

b = pd.DataFrame(
    {
        'k': ['aa', 'ab', 'ac', 'ba', 'bb', 'bc'],
        'v': [1.0,  1.5,  2.1,  3,   4,  1.7],
        'y': [1998] * 6,
    }
)

c = pd.concat([a, b])
print(c.loc[c.k.str[-1] == 'c'])

print("\n\n C = ")
print(c)


print('sum of v of rows where k starts with "a" grouped by y:')
rows = c.k.str.startswith('a')
print(c.loc[rows].groupby(['y']).sum(numeric_only=True))
