#!/bin/sh

# Taken from https://stackoverflow.com/questions/750172

export OLD_EMAIL=${1:?}
export NEW_EMAIL=${2:?}
export NAME

git filter-branch --env-filter '
if test "$GIT_COMMITTER_EMAIL" = "$OLD_EMAIL"; then
    export GIT_COMMITTER_EMAIL="$NEW_EMAIL"
fi
if test "$GIT_AUTHOR_EMAIL" = "$OLD_EMAIL"; then
    export GIT_AUTHOR_EMAIL="$NEW_EMAIL"
fi
' --tag-name-filter cat -- --branches --tags
