#!/bin/sh

# Note that git-filter-branch is generally considered obsolete.  Instead, look at
# git://github.com/newren/git-filter-repo

# Replace spaces with tabs in all files throughout history
this="$PWD/$0"
if test -z "$REPLACE_TABS"; then
	git filter-branch --tree-filter "git ls-files | REPLACE_TABS=1 xargs $this" HEAD
else
	trap 'rm -f $tmp' 0
	tmp=$(mktemp)
	for x; do
		unexpand -t 8 "$x" > "$tmp" &&
		mv "$tmp" "$x"
	done
fi
exit 0

# Replace author and committer throughout history
# Straight from the manpage:
git filter-branch --env-filter '
   if test "$GIT_AUTHOR_EMAIL" = "root@localhost"; then
	   GIT_AUTHOR_EMAIL=john@example.com
   fi
   if test "$GIT_COMMITTER_EMAIL" = "root@localhost"; then
	   GIT_COMMITTER_EMAIL=john@example.com
   fi
' -- --all
