
cc_library(
	name = "xutil",
	srcs = ["xutil.c"],
	hdrs = ["//include:xutil.h"],
	includes = ["../include"],
	visibility = ["//main:__pkg__"],
)

cc_library(
	name = "ringbuf",
	srcs = ["ring-buffer.c"],
	hdrs = ["//include:ring-buffer.h"],
	includes = ["../include"],
	visibility = ["//main:__pkg__"],
)

cc_library(
	name = "stack",
	srcs = ["stack.c"],
	includes = ["../include"],
	hdrs = ["@//include:stack.h"],
	visibility = ["//main:__pkg__"],
)
