
cc_library(
	name = "xutil",
	srcs = ["xutil.c"],
	hdrs = ["xutil.h"],
	includes = ["."],
	visibility = ["//main:__pkg__"],
)

cc_library(
	name = "ringbuf",
	srcs = ["ring-buffer.c"],
	hdrs = ["ring-buffer.h"],
	includes = ["."],
	visibility = ["//main:__pkg__"],
)

cc_library(
	name = "stack",
	srcs = ["stack.c"],
	hdrs = ["stack.h"],
	includes = ["."],
	visibility = ["//main:__pkg__"],
)
