#!/bin/sh

# Using getopts means that all flags must appear before non-option arguments

# getopts is Posix.  getopt provides long options, but is non-standard.
# But (except for ordering of options), it is trivial to implement similar
# functionality with getopts.

usage() {
	cat <<- EOF
	usage: $(basename $0) [-ch] [-d value|-dvalue] [--help] [--long-opt=value] [--long-bool] [--] args ...

	Long options must come after all short options and before all positional arguments.

	-h, --help         print this message
	-c                 specify boolean C
	-d val | -dval     set value for d flag
	--long-opt=val     set value with a long option
	--long-bool        a boolean flag with long option
	EOF
	exit 0
}

die() { echo "$@" >&2; exit 1; }

parse_opts() {
	# The leading : puts getops in silent mode so it doesn't print stupid error messages
	# subsequent colons indicate that the previous flag takes an argument
	while getopts ":cd:h-" opt; do
		case $opt in
		c) FLAG_C=1;;
		d) FLAG_D=$OPTARG;;
		h) usage;;
		-) break;;
		:) die "option -$OPTARG requires a value";;
		?) die "illegal option -$OPTARG (-h for usage)";;
		esac
	done
}

parse_long_opts() {
	local stop
	OPTIND=1
	while test -n "$1" && test -z "$stop"; do
		case "$1" in
		--help) usage;;
		--long-bool) LONG_BOOL=;;
		--long-opt*)
			LONG_OPT=${1#*=}
			if test "$1" = "$LONG_OPT"; then
				die '--long-opt requires a value'
			fi;;
		--) stop=1;;
		--*) die "Unknown/invalid option $1";;
		*) return;;
		esac
		shift; : $((OPTIND+=1))
	done
}

parse_opts "$@"
shift $(($OPTIND-1))   # Reset OPTIND=1 if you call getops again
parse_long_opts "$@"
shift $(($OPTIND-1))   # Reset OPTIND=1 if you call getops again

for name in FLAG_C FLAG_D LONG_BOOL LONG_OPT; do
	eval "echo $name=\$$name \${$name+(set)}"
done

echo args: "$@"
