#!/bin/sh

cat << EOF
A simple example using an interpolating heredoc
to write multiple lines of text.  Here variables
are expanded.
EOF

cat << 'EOF'
In the quoted heredoc, no variable interpolation
occurs.
EOF

