#!/bin/sh
# Simple demonstration parsing the file header to produce usage
#
# usage: @NAME@ [-h] required_argument [optional_argument ...]
#
# options:
#     -h/--help         print usage statement

if printf '%s\n' "$@" | sed '/^--$/q' | grep -qE -- '^(-h|--help)$'; then
	sed -nE '2,/^$/{/^$/q; s/# ?//; s|@NAME@|'"${0##*/}|"'; p;}' "$0"
	exit
fi
