#!/bin/sh

# usage: @NAME@ [-h] required_argument [optional_argument ...]
#
# options:
#   -h         print usage statement
##############################################################

case "$1" in
-h)
	sed -nE "/^##/q; s|@NAME@|$(basename $0)|; 1!s/# ?//p;" "$0"
	exit
esac
