#!/bin/sh

# This is an example of the hook I just added to .git/local-hooks/prepare-commit-msg
# Make .git/local-hooks a symbolic link to this directory

if ! git interpret-trailers --parse "$1" | grep -q "^type:"; then

	echo >> "$1"
	git diff-index --cached --name-status HEAD -- |
	awk 'NR==1{
		name = $2;
		i = index(name, "/");
		tag = i ? substr(name, 0, i - 1) : name;
		printf "type: %s\n", tag;
	}' >> "$1"
fi
