#!/bin/sh

# Make .git/hooks/prepare-commit-msg a symbolic link to this.
# It will auto inject a trailer based if none is present.

if ! git interpret-trailers --parse "$1" | grep -q "^Type:"; then
	echo
	git diff-index --cached --name-only HEAD \
	| awk 'seen[$1]++ == 0 { printf "Type: %s\n", $1 }' FS=/
fi >> "$1"
