#!/bin/sh

# Test arithperm

out=$(./arithperm 1 2 3)
if test "$out" != '(1 + 2) + 3 = 6
(1 - 2) + 3 = 2
(1 * 2) + 3 = 5
(1 / 2) + 3 = 3.5
(1 + 2) - 3 = 0
(1 - 2) - 3 = -4
(1 * 2) - 3 = -1
(1 / 2) - 3 = -2.5
(1 + 2) * 3 = 9
(1 - 2) * 3 = -3
(1 * 2) * 3 = 6
(1 / 2) * 3 = 1.5
(1 + 2) / 3 = 1
(1 - 2) / 3 = -0.333333
(1 * 2) / 3 = 0.666667
(1 / 2) / 3 = 0.166667
1 + (2 + 3) = 6
1 + (2 - 3) = 0
1 + (2 * 3) = 7
1 + (2 / 3) = 1.66667
1 - (2 + 3) = -4
1 - (2 - 3) = 2
1 - (2 * 3) = -5
1 - (2 / 3) = 0.333333
1 * (2 + 3) = 5
1 * (2 - 3) = -1
1 * (2 * 3) = 6
1 * (2 / 3) = 0.666667
1 / (2 + 3) = 0.2
1 / (2 - 3) = -1
1 / (2 * 3) = 0.166667
1 / (2 / 3) = 1.5'
then
	echo "Got unexpected: '$out'" >&2
	exit 1
fi

# Check if bc is installed
if ! test "$(echo 1 + 1 | bc)" = 2; then
	exit 77
else
	./arithperm 1 4 5 7.8 | while IFS== read lhs rhs; do
		if ! { echo "$lhs" | bc -l | tr -d \\n; echo "$rhs"; } \
				| awk '(NF != 2)  || ($2 - $1 > eps ) ||
					($1 - $2) > eps{ exit 1}' eps=.01; then
			echo "arithperm incorrectly reported $lhs = $rhs" >&2
			exit 1
		fi
	done
fi
