
cc_library(
	name = "xutil",
	srcs = ["lib/xutil.c"],
	hdrs = ["include/xutil.h"],
	includes = ["include"],
	visibility = ["//main:__pkg__"],
)

cc_library(
	name = "ringbuf",
	srcs = ["lib/ring-buffer.c"],
	hdrs = ["include/ring-buffer.h"],
	includes = ["include"],
	visibility = ["//main:__pkg__"],
)

cc_library(
	name = "stack",
	srcs = ["lib/stack.c"],
	includes = ["include"],
	hdrs = ["include/stack.h"],
	visibility = ["//main:__pkg__"],
)
