#!/bin/sh

# test calc.c


RV=0
test_string() {
	out=$(echo "$1" | ./calc)
	if test "$out" != "$2"; then
		echo "On input:'$1', expected output '$2', got '$out'" >&2
		RV=1
	fi
}

test_string '1 1+p' '     2'
test_string '5 6*p' '    30'
test_string '7 3-p' '     4'
test_string '7 3-2wp' ' 4'
test_string '7 2/p' '   3.5'
exit $RV
