#!/bin/sh

# Check coverage of calc.c.  If configured without --coverage in CFLAGS,
# this will likely just get skipped.  (eg, configure with
# CFLAGS='--coverage -g -O0' to run this test)

progs='calc ring-buffer dynamic list dynamic-read
	udp-server udp-client'

if ! test -f calc.gcda; then
	exit 77
fi
RV=0

for file in $progs; do
	if test -f .libs/$file.gcno; then
		arg='-o .libs'
	else
		unset arg
	fi
	gcov $file $arg
	if grep '#####' $file.c.gcov |
			sed \
			-e '\@/\* uncovered \*/@d' | grep .; then
		echo The above lines of $file were not executed during testing
		RV=1
	fi >&2
done
exit $RV
