#!/bin/sh

exe=./dynamic-array

die() { test -n "$*" && echo "$*"; exit 1; } >&2

expect() {
	printf "$1" | $exe | perl -w -0777 -e 'my $m = <STDIN>;
		die "Got \"$m\", expected \"$ARGV[0]\"" if $m ne $ARGV[0]' "$2" || die
	test "$(printf "$1" | $exe | $exe)" = "$(printf "$1")" \
		|| die "Failed to invert '$1"
}

nl='
'
expect 'foo bar' 'foo bar'
