#!/bin/sh

exe=./list
args=

RV=0
# Run a string through and validate the output
test_string() {
	export COLUMNS
	out=$(printf "$1" | $exe $args 2>&1)
	if test "${2+set}" = set && test "$out" != "$(printf "$2")"; then
		echo "On input:'$1', expected output '$2', got '$out'" >&2
		return 1
	fi
	return 0
}

nl='
'
test_string '1 3 5 3 7 2' "1 3 5 7 2${nl}2 7 5 3 1"
( args=, test_string '1,3,5,3,7,2' "1,3,5,7,2${nl}2,7,5,3,1") || RV=1
( COLUMNS=10 test_string '1 3' "1${nl}3${nl}3${nl}1" ) || RV=1

exit $RV
