#!/bin/sh

exe=${0%-test}
args=

RV=0
# Run a string through and validate the output
test_string() {
	out=$(printf "$1" | $exe $args 2>&1)
	if test "${2+set}" = set && test "$out" != "$(printf "$2")"; then
		echo "On input:'$1', expected output '$2', got '$out'" >&2
		RV=1
	fi
}

test_string '1 3 5 3 7 2' '1 3 5 7 2'
args=, test_string '1,3,5,3,7,2' '1,3,5,7,2'

exit $RV
