#!/bin/sh

exe=./dynamic-read

die() { echo "$*"; exit 1; } >&2

expect() {
	out=$(printf "$1" | $exe)
	if ! test "$out" = "$2"; then
		die "Got $out, expected '$2' for inpput '$1'"
	fi
}

nl='
'
expect 'foo bar\none two\n' "rab oof${nl}owt eno"
expect 'foo\nbar' "oof${nl}rab"
expect abc cba

count=0
for i in *; do
	test -f "$i" || continue
	# Ignore the file that this is writing to
	test "$i" = $(basename $0).log && continue
	: $(( count += 1 ))
	if ! $exe "$i" | $exe | cmp - "$i"; then
		echo "Okay on $count files, but failed on $i" >&2
		exit 1
	fi
done
if test "$count" -lt 10; then
	echo "Not enough tests" >&2
	exit 77
fi
