#!/bin/sh

trap 'rm -rf $tmpdir' 0
tmpdir=$(mktemp -d)
mkdir -p $tmpdir
perl -E 'while(++$i < 16) { printf("%2d:foo ", $i);
	say map { (q(a)..q(z))[rand(26)] } 1 .. rand(10)+8 }' > $tmpdir/file

rm -f $tmpdir/file.idx

validate_line() {
	output="$(./read-indexed $tmpdir/file $1 | awk '{print $1}')"
	if ! test "$output" = $1:foo; then
		printf "Unexepected output for line %d: %s\n", "$1" "$output" >&2
		exit 1
	fi
}

yes | nl | sed 15q | while read i y; do
	validate_line $i
done

./read-indexed $tmpdir/file 16 2> /dev/null

exit 0
