#!/bin/sh

exe=./dynamic-read

die() { echo "$*"; exit 1; } >&2

out=$(printf 'foo bar\none two\n' | $exe)
if ! test "$out" = 'rab oof
owt eno';
then echo "Got $out" >&2; exit 1; fi

got=$( printf abc | $exe )
if ! test "$got" = cba; then
	die "Failed on single line with no newline.  Got '$got', expected cba"
fi

count=0
for i in *.c *; do
	test -f "$i" || continue
	: $(( count += 1 ))
	if ! $exe "$i" | $exe | cmp - "$i"; then
		echo "Okay on $count files, but failed on $i" >&2
		exit 1
	fi
done
