#!/bin/sh

exe=./dynamic-read

die() { echo "$*"; exit 1; } >&2

out=$(printf 'foo bar\none two\n' | $exe)
if ! test "$out" = 'rab oof
owt eno';
then echo "Got $out" >&2; exit 1; fi

out=$(printf 'foo\nbar' | $exe)
if ! test "$out" = 'oof
rab'; then
	die "$LINENO: Got $out"
fi

out=$( printf abc | $exe )
if ! test "$out" = cba; then
	die "Failed on single line with no newline.  Got '$out', expected cba"
fi

count=0
for i in *.c *; do
	test -f "$i" || continue
	# Ignore the file that this is writing to
	test "$i" = $(basename $0).log && continue
	: $(( count += 1 ))
	if ! $exe "$i" | $exe | cmp - "$i"; then
		echo "Okay on $count files, but failed on $i" >&2
		exit 1
	fi
done
if test "$count" -lt 10; then
	echo "Not enough tests" >&2
	exit 77
fi
