#!/bin/sh

# Simple test of the udp socket
trap 'rm -f $output' 0
output=$(mktemp)

./udp-server > $output &
for i in $(seq 10); do
	echo foo | ./udp-client
done
echo q | ./udp-client

grep -q foo $output
