
# My minimal debian image
FROM debian
RUN printf 'set editing-mode vi\nset keymap vi\n' > /etc/inputrc
RUN printf 'bind -v\n' > /root/.editrc
RUN apt-get update
RUN apt-get -y install aptitude
RUN aptitude install -y sudo
RUN aptitude install -y less
RUN aptitude install -y vim
RUN aptitude install -y perl
RUN aptitude install -y gcc
RUN aptitude install -y make
RUN aptitude install -y nmap
RUN apt-get update && aptitude install -y gdb
RUN aptitude install -y git
RUN aptitude install -y libncurses-dev
RUN aptitude install -y ncurses-doc
RUN aptitude install -y golang
RUN aptitude install -y manpages
RUN aptitude install -y man-db

ARG user=docker_user
ARG uid=1000
ARG dest_home=/home/$user

RUN adduser --uid $uid --quiet $user
ENV USER=$user
RUN printf "root ALL=(ALL) ALL\n" > /etc/sudoers
RUN printf "$user ALL=(ALL) NOPASSWD:ALL\n" >> /etc/sudoers
copy bashrc ${dest_home}/.bashrc
copy gitconfig ${dest_home}/.gitconfig

RUN echo '[user]' > ${dest_home}/.gitconfig-user
RUN echo "name = ${USER}" >> ${dest_home}/.gitconfig-user
RUN echo "email = ${USER}@foo.org" >> ${dest_home}/.gitconfig-user

workdir ${dest_home}
CMD sudo DOCKER=debian -u "$USER" bash
