#!/bin/bash

pgid=$(ps -o pgid= $$ | tr -d ' ')
trap 'kill -- -$pgid' 0
# Generate statsd data and send to $1:$2
ip=${1?}
port=${2?}

report() {
	echo "$1"
}

{
	# Gauges
	i=1800
	while true; do
		case $(( i += RANDOM % 16 - 8 )) in
		3600|0) i=1800;;
		esac
		report "my_gauge:$i|g"
		sleep 1
	done &

	while sleep 1; do
		test $((v++)) -gt 3600 && v=0
		report "fast_montonic:$v|g"
	done &
	while sleep 60; do
		test $((v++)) -gt 3600 && v=0
		report "slow_montonic:$v|g"
	done &

	# Counters
	while sleep 1; do
		report 'fast_counter:1|c'
		report 'fast_sampled:1|c|@0.1'
	done &

	# Timers
	while sleep 10; do
		report "my_timer:$((RANDOM % 256))|ms"
	done &
} | ncat -u $ip $port
wait
