#!/bin/sh

# Get all roles for a given user from a gcp project.  If input
# is from a tty, query gcloud to get the iam policy.  Otherwise,
# it is expected that the input stream is the json formatted
# policy.  (eg, the output of gcloud projects --format=json get-iam-policy)

trap 'rm -f "$temp"' 0
temp=$(mktemp)

if test -t 0; then
	gcloud projects --format=json get-iam-policy "${PROJECT?}"
else
	cat
fi > "$temp"

for user; do
	echo $user:
	< "$temp" jq -rc '.bindings[] | select( .members[] | test("'"$user"'")) | "\t" + .role'
done
