#!/bin/sh

# Terminate jq early when a condition is matched
jq '.foo , if .bar == null then null | halt_error(1) else empty end' << EOF
{
  "foo": 5,
  "bar": 2
}
{
  "foo": 3
}
{
  "foo": 2,
  "bar": 2
}
EOF

