#!/bin/sh

# Remove one matching element
sed -e 's/#.*//' << \EOF  |
{
      "foofoo": {
        "barbar": [
          {
            "foo": "0000",
            "bar": "aaaa"
          },
          {
            "foo": "1111",
            "bar": "bbbb"
          },
          {      # This element will be removed
            "foo": "2222",
            "bar": "cccc"
          }
          ]
      }
}
EOF
jq '.foofoo.barbar |= map(select(.bar !="cccc"))'
