#!/bin/sh

# Filter removes items from the access member
cat << EOF |
{
  "access": [
    {
      "role": "WRITER",
      "specialGroup": "projectWriters"
    },
    {
      "role": "OWNER",
      "specialGroup": "projectOwners"
    },
    {
      "role": "READER",
      "specialGroup": "projectReaders"
    }
  ],
  "creationTime": "1555555555555",
  "datasetReference": {
    "datasetId": "random_dataset",
    "projectId": "some-project-id"
  },
  "etag": "base64string",
  "id": "some id",
  "kind": "bigquery#dataset",
  "lastModifiedTime": "1555555666666",
  "location": "US",
  "selfLink": "https://bigquery.googleapis.com/bigquery/v2/projects/dataset"
}
EOF
jq '.access = [ {"role": "OWNER", "specialGroup": "projectOwners"} ]'
