#!/bin/sh

# Select all those objects in which a sub-member array contains a particular string

for t in a b c; do
	printf "%s: " "$t"; echo '{ "q": {"m": ["a","b"]}, "z": {"m": ["b", "c"]}}' |

jq -c "map_values( select( .m | index(\"$t\")))"

done

for t in a b c; do
	printf "%s: " "$t"; echo '[ { "m": ["a","b"], "r": "foo"}, { "m": ["b", "c"], "r":"bar" }]' |

jq -c "map_values( select( .m | index(\"$t\")))[] | .r"

done



exit

# output:


a: {"q":{"m":["a","b"]}}
b: {"q":{"m":["a","b"]},"z":{"m":["b","c"]}}
c: {"z":{"m":["b","c"]}}
