#!/bin/sh

# Select all those objects in which a sub-member array contains a particular string

for t in a b c; do
	printf "%s: " "$t";
	echo '{
		"q": {"m": ["a","b"]},
		"z": {"m": ["b","c"]},
		"a": {"m": ["z","y"]}
	}' |

jq -c ".[] |= select( .m | index(\"$t\"))"
# jq -c "map_values( select( .m | index(\"$t\")))"

done

for t in a b c; do
	printf "%s: " "$t"
	echo '[
		{ "m": ["a","b"], "r": "foo"},
		{ "m": ["b","c"], "r": "bar"},
		{ "m": ["z","c"], "r": "bar2"},
		{ "m": ["z","c"], "r": "bar3"},
		{ "m": ["z","c"], "r": "bar4"}
	]' |

jq -c ".[] |= select( .m | index(\"$t\"))[]  "
# jq -c "map_values( select( .m | index(\"$t\")))[] | .r"

done

printf "%s: " "b"; echo '[
	{ "members": ["a","z"], "role": "foo1"},
	{ "members": ["a","b"], "role": "foo2"},
	{ "members": ["a","z"], "role": "foo3"},
	{ "members": ["b","z"], "role": "foo4"},
	{ "members": ["a","b"], "role": "expet"},
	{ "members": ["k", "c"], "role":"bar" }]
	' |
jq -c ' .[] | select( .members | index("b")) | .role'
# jq -c '.bindings | map_values( select( .members | index("b"))) '
exit
#output
a: {"q":{"m":["a","b"]}}
b: {"q":{"m":["a","b"]},"z":{"m":["b","c"]}}
c: {"z":{"m":["b","c"]}}
