#!/bin/sh

data() { cat << EOF
[
  {
    "uuid": "832390ed-58ed-4338-bf97-eb42f123d9f3",
    "name": "Nacho"
  },
  {
    "uuid": "5b55ea5e-96f4-48d3-a258-75e152d8236a",
    "name": "Taco"
  },
  {
    "uuid": "a68f5249-828c-4265-9317-fc902b0d65b9",
    "name": "Burrito"
  }
]
EOF
}

data | jq -r '.[] | select( .name == "Burrito") | .uuid '
# Use a variable to select
data | jq --arg target Nacho -r '.[] | select( .name == $target) | .uuid'

strings() { cat << EOF
[
    "832390ed-58ed-4338-bf97-eb42f123d9f3",
    "Nacho",
    "5b55ea5e-96f4-48d3-a258-75e152d8236a",
    "Taco",
    "a68f5249-828c-4265-9317-fc902b0d65b9",
    "Burrito"
]
EOF
}

doit() {
	echo "$1":
	strings | jq -r "$1"
}
# select all string that match the regex (PCRE) "a"
doit '.[] | select( test("a"))'
