#!/bin/sh

date +%s \
| jq -c --slurp --raw-input 'split("\n")[:-1] | map({
	raw:  (. | strptime("%s") ),
	rawdate:(. | strptime("%s") | todate ),
	date: (. | strptime("%s") | todate[0:10 ]),
	time: (. | strptime("%s") | todate[11:19])
})'
