#!/bin/sh

# From https://unix.stackexchange.com/questions/476536/how-to-find-and-replace-multiple-field-values-using-jq

jq '
  # Apply f to composite entities recursively, and to atoms
  def walk(f):
    . as $in
    | if type == "object" then
       reduce keys[] as $key
         ( {}; . + { ($key):  ($in[$key] | walk(f)) } ) | f
    elif type == "array" then map( walk(f) ) | f
    else f
    end;
  walk(.name?="XXX")
'  << EOF
{
  "email": "xxx",
  "pass": "yyy",
  "contact": [
    {
      "id": 111,
      "name": "AAA"
    }
  ],
  "lname": "YYY",
  "name": "AAA",
  "group": [
    {
      "name": "AAA",
      "lname": "YYY"
    }
  ]
}
EOF
