#!/bin/sh


show_node() {
	pod=$1

	test "$pod" = NAME && return  # Special case so we can read output directly from kubectl get pods

	node=$(kubectl get pod ${pod:?} -o jsonpath='{.spec.nodeName}') || exit
	type=$(kubectl get node $node \
		-o jsonpath='{.metadata.labels.node\.kubernetes\.io/instance-type}') || exit
	printf '%s' "$type"
}


if test $# = 0; then
	if test -t 0; then kubectl get pod; else cat ; fi |
	while read line; do printf '%s\t%s\n' "$line" "$(show_node $line)"; done
else
	for pod; do printf '%s\t%s\n' "$pod" "$(show_node "$pod")"; done
fi
