#!/bin/sh

display_node() {
	kubectl get pods --all-namespaces -o wide --field-selector spec.nodeName="$1"
}


if test $# = 0; then
	set -- $(kubectl get nodes --no-headers | awk '{print $1}')
fi

for node;  do
	display_node "$node"
done
