apiVersion: apps/v1
kind: Deployment
metadata: { name: helloworld }
spec:
  selector: { matchLabels: { app: helloworld } }
  replicas: 1
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
      - name: helloworld
        image: alpine:latest
        command: ["/bin/sh"]
        args: ["-c", "date; sleep 10; date"]
