apiVersion: apps/v1
kind: Deployment
metadata: { name: helloworld }
spec:
  selector: { matchLabels: { app: helloworld } }
  replicas: 1
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
      - name: helloworld
        image: alpine:latest
        command: ["/bin/sh"]
        args: ["-c", "date; echo \"$GREETING, ${NAME}!\"; sleep 4; date"]
        env:
        - name: GREETING
          valueFrom:
            configMapKeyRef:
              name: hello-world-configmap
              key: properties.greeting
        - name: NAME
          valueFrom:
            configMapKeyRef:
              name: hello-world-configmap
              key: properties.name
