#!/bin/sh

# Check coverage.  If configured without --coverage in CFLAGS,
# this will likely just get skipped.  (eg, configure with
# CFLAGS='--coverage -g -O0' to run this test)

if ! test -f .libs/hashmap.gcda; then
	exit 77
fi
RV=0

for file in \
	hashmap \
; do
	if test -f .libs/$file.gcda; then
		arg='-o .libs'
	else
		unset arg
	fi
	gcov "$file" $arg
	if < "$file".c.gcov sed \
		-e '\@{ /\* uncovered block \*/@,'"$( :
			)"'\@} /\* end uncovered \*/@d' \
		-e '/#####/!d' \
		-e '\@/\* uncovered \*/@d' \
		| grep .
	then
		echo "FAIL: The above lines of $file were not executed during testing"
		RV=1
	fi >&2
done
exit $RV
