#!/bin/sh

if test "${GITLAB_HOME?}" = "${GITLAB_HOME#/}"; then
	echo "GITLAB_HOME must be an absolute path.  Set to: '$GITLAB_HOME'" >&2
	exit 1
fi

docker run --detach \
	--hostname gitlab.example.com \
	--publish 1043:443 \
	--publish 1080:80 \
	--publish 1022:22 \
	--name gitlab \
	--restart always \
	--volume $GITLAB_HOME/config:/etc/gitlab \
	--volume $GITLAB_HOME/logs:/var/log/gitlab \
	--volume $GITLAB_HOME/data:/var/opt/gitlab \
	--shm-size 256m \
	gitlab/gitlab-ee:latest
