[package]
name = "bindgen"
version = "0.1.0"
authors = ["William Pursell <william.r.pursell@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]


[build-dependencies]
bindgen = "0.53.1"

