#!/bin/sh


# List all repositories
aws ecr describe-repositories


# List the images in a repo
list_images() {
	for repo_name; do
		aws ecr list-images \
			--repository-name ${repo_name?} \
			--region ${region-us-west-2} \
			--query 'imageIds[*].imageTag' \
			--output text \
		| tr \\t \\n | sort -V
	done
}


# Get the size of a repo
get_size() {
	for tag; do
		aws ecr describe-images --repository-name ${repo} \
			--image-ids imageTag="$tag" --query "imageDetails[0].imageSizeInBytes"
	done
}
