#!/bin/sh


# List all repositories
aws ecr describe-repositories | jq -r .repositories'[].repositoryName'


# List the images in a repo
list_images() {
	for repo_name; do
		aws ecr list-images \
			--repository-name ${repo_name?} \
			--region ${region-us-west-2} \
			--query 'imageIds[*].imageTag' \
			--output text \
		| tr \\t \\n | sort -V
	done
}


# Get the size of a repo
get_size() {
	for tag; do
		aws ecr describe-images --repository-name ${repo} \
			--image-ids imageTag="$tag" --query "imageDetails[0].imageSizeInBytes"
	done
}


# Delete an image
remove_image() {
	for image; do
		aws ecr batch-delete-image --repository-name ${repo} \
			--region ${region-us-west-2} --image-ids imageTag="${image}"
	done
}


# Show most recently pushed image
aws ecr describe-images \
	--repository-name ${repo} \
	--query 'sort_by(imageDetails, &imagePushedAt)[-1]' \
| jq -r '.imageTags[]'
