#!/bin/sh

# See: https://cloud.google.com/logging/docs/view/query-library

gcloud logging read "(
	logName : projects/${PROJECT_ID?}/logs/cloudaudit.googleapis.com
	AND resource.type=k8s_cluster
	AND timestamp>=\"2024-05-07T00:00:00\" AND timestamp<=\"2024-05-09T00:00:00Z\"
)" \
	--project=${PROJECT_ID} --format=json --limit 50
