#!/usr/bin/env python3

import sys


print("A string to stdout")
print("A string to stderr", file=sys.stderr)
print("two", "strings")
print("two", "strings", "with commas", sep=',')

"""
>>> help (print)
Help on built-in function print in module builtins:

print(...)
    print(value, ..., sep=' ', end='\n', file=sys.stdout, flush=False)

    Prints the values to a stream, or to sys.stdout by default.
    Optional keyword arguments:
    file:  a file-like object (stream); defaults to the current sys.stdout.
    sep:   string inserted between values, default a space.
    end:   string appended after the last value, default a newline.
    flush: whether to forcibly flush the stream.

"""

