#!/usr/bin/env perl
# A random collection of symbols.
# printf '\xf0\x9f\x9b\x91 \U1f6d1'  # Shell printf

# Mapping from a code-point to a byte sequence is a bit
# convoluted.  The point code \U1f6d1 uses the template
# 11110xxx  10xxxxxx  10xxxxxx  10xxxxxx

# 1f6d1 == 0 0001 1111 0110 1101 0001, so we fill in the
# template to get:
# 11110xxx  10xxxxxx  10xxxxxx  10xxxxxx
#      ^^^    ^^^^^^    ^^^^^^    ^^^^^^
#      000    011111    011011    010001
# 11110000  10011111  10011011  10010001
# 0xf0      9f         9b        91
#

use 5.12.0;
use Unicode::UCD "charinfo";
use Data::Dumper;


my @samples = (
	'f09f9b91',  # A stop sign: 🛑  \U1f6d1
	'e29c8b',    # A yellow hand  ✋
	'f09f8c80',  # Debian symbol 🌀
	'f09f8cb9',  # A rose 🌹
	'e2888a',    # ∊
	'e28888',    # ∈
	'e280a6',    # ellipses …
	'e2889e',    # ∞
	'c2b1',      # ±
	'cf80',      # π
	'e28a86',    # ⊆   Subset
	'e284a4',    # ℤ
	'e29ca8',    # ✨
	'e29c85',    # ✅
);
printf "%s", pack "H*", $_ foreach @samples; print "\n";
# print Dumper(charinfo(0x1f6d1));

sub print_range {
	printf("%x .. %x: ", $_[0], $_[1]);
	foreach my $x ($_[0]..$_[1]) {
		my $s = sprintf('%x', $x);
		printf "%s", pack "H*", $s;
	}
	print "\n";
}

sub print_32 { print_range $_[0], $_[0] + 31; }
print_32 0xe0b880;
print_32 0xe0b8a0;
print_32 0xe0b980;
print_32 0xe28a80;  # Set relations
print_range 0xe58580, 0xe5859f;
print_range 0xe585a0, 0xe585bf;
print_range 0xe58a90, 0xe58aaf;
print_range 0xe58ab0, 0xe58abf;
print_range 0xe58c90, 0xe58caf; # Some Chinese characters
print_range 0xe58cb0, 0xe58ccf;
print_range 0xe59080, 0xe5909f;
print_range 0xe590a0, 0xe590bf;

print_range 0xe38190, 0xe381af;
print_range 0xe381b0, 0xe381bf;
print_range 0xe29c82, 0xe29c9f;
print_range 0xe29ca0, 0xe29cbf;

# use open ":std", ":encoding(UTF-8)";
binmode STDOUT, ':encoding(UTF-8)';

print "\\U1f6d1: " . chr(0x1f6d1) . "\n";

@samples = (
	[0x2589..0x25A0],  # Block elements
	[0x2B00..0x2B56],  # Miscellaneous symbols and arrows
	[9800..9811],      # Miscellaneous symbols
	[9812..9831],      #   chess/card symbols
	[9833..9839],      #   music
	[9855..9865],
	[9889..9899],
	[913..991],        # Greek an Coptic
);

my $block = "";
my $previous_block = "";

foreach my $range (@samples) {
	my $first = $$range[0];
	my $info = charinfo($first);
	# print Dumper($info);
	$block = $$info{block};
	say $block if $block ne $previous_block;
	$previous_block = $block;

	print chr($_) . (( ($_ % 16) == (($first - 1) % 16)) ? "\n" : "  ")
		foreach (@$range);
	print "\n";
}


# perl -MUnicode::UCD=charinfo -MData::Dumper -e 'print Dumper(charinfo(0x1f6d1))'
__DATA__

for i in แ ก้ ไ ... ; do
	printf "$i\t";
	printf $i | xxd;
done | awk '{$2=""}1'
แ  e0b9 81 ...
ก้  e0b8 81e0 b989 ......
ไ  e0b9 84 ...
ข  e0b8 82 ...
เ  e0b9 80 ...
พิ่  e0b8 9ee0 b8b4 e0b9 88 .........
ม  e0b8 a1 ...
ฟั  e0b8 9fe0 b8b1 ......
ง  e0b8 87 ...
ก์  e0b8 81e0 b98c ......
ชั  e0b8 8ae0 b8b1 ......
น  e0b8 99 ...
ใ  e0b9 83 ...
ช้  e0b8 8ae0 b989 ......
แ  e0b9 81 ...
ท  e0b8 97 ...
น  e0b8 99 ...
ที่  e0b8 97e0 b8b5 e0b9 88 .........
แ  e0b9 81 ...
ล  e0b8 a5 ...
ะ  e0b8 b0 ...
เ  e0b9 80 ...
พื่  e0b8 9ee0 b8b7 e0b9 88 .........
อ  e0b8 ad ...
ต  e0b8 95 ...
ร  e0b8 a3 ...
ว  e0b8 a7 ...
จ  e0b8 88 ...
ว่  e0b8 a7e0 b988 ......
า  e0b8 b2 ...
ไ  e0b9 84 ...
ม่  e0b8 a1e0 b988 ......
ถู  e0b8 96e0 b8b9 ......
ก  e0b8 81 ...
เ  e0b9 80 ...
รี  e0b8 a3e0 b8b5 ......
ย  e0b8 a2 ...
ก  e0b8 81 ...

แก้ไขเพิ่มฟังก์ชันใช้แทนที่และเพื่อตรวจว่าไม่ถูกเรียก
ฟิกซ์เจอร์สำหรับแก้ไขและคืนค่าฟังก์ชันชั่วคราว.
