#!/bin/sh

# Send a GET to the endpoint $1
curl -Ssf -H "Accept: application/vnd.github+json" \
	-H "Authorization: Bearer ${GITHUB_TOKEN?}" \
	-H "X-GitHub-Api-Version: 2022-11-28" \
	https://api.github.com/${1?} |
jq -r .[]
