#!/usr/bin/env python3
# vim: sw=8 ts=8 sts=8 noet

# Collect all tickets that contain the label in first argument

from jira import JIRA, JIRAError
import os
import sys
from http import HTTPStatus
from datetime import datetime


jira_url = os.environ['JIRA_URL']
jira_token = os.environ['JIRA_TOKEN']
email = os.environ['EMAIL']


def get_time(timestamp):
	if timestamp[-3] != ':':
		timestamp = timestamp[0:-2] + ':' + timestamp[-2:]
	return datetime.fromisoformat(timestamp)

def main():
	if len(sys.argv) == 1:
		print(f"usage: {sys.argv[0]} label")
		sys.exit(0)

	jira = JIRA(jira_url, basic_auth=(email, jira_token))
	for label in sys.argv[1:]:
		get_tickets(label, jira)


def get_tickets(label, jira):
	max_results = 50
	all_issues = []
	start_at = 0
	while True:
		issues = jira.search_issues(
			f'labels = {label}',
			startAt=start_at,
			maxResults=max_results,
		)
		all_issues.extend(issues)
		if len(issues) < max_results:
			break
		start_at += max_results

	print('\n'.join([str(x) for x in all_issues]))



try:
	main()
except KeyboardInterrupt:
	sys.exit(1)
except JIRAError as e:
	raise SystemExit(f'{e.status_code}: {HTTPStatus(e.status_code).phrase}')
