#!/bin/sh

curl -Ssf \
	-u "${EMAIL?}:${JIRA_TOKEN?}" \
	-H 'Content-Type: application/json' \
	"${JIRA_URL?}/rest/api/2/search?jql=assignee=currentuser()" \
| jq -rc '.issues[] | [.key, .created, .fields.summary] | @tsv'
