#!/bin/bash

start=0
incr=30

while
	curl -Ssf -G \
		-d startAt=${start} \
		-d maxResults=${incr} \
		-H 'Content-Type: application/json' \
		-u "${EMAIL?}:${JIRA_TOKEN?}" \
		"${JIRA_URL?}/rest/api/2/component" \
	| jq '.values[], if .isLast then null | halt_error else empty end'
do
	: $(( start += $incr ))
done \
| if test -n "$brief"; then
	{ echo '{"id": "id", "name": "name", "description": "description"}'; cat ; } \
	| jq -rc '[ .id, .name, .description ] | @tsv'
else
	cat
fi
