#!/bin/sh

tabs 20,+16,+40

header=$(printf 'key\tstatus\tcreated at\tsummary')
curl -Ssf --ca-native \
	-u "${EMAIL?}:${JIRA_TOKEN?}" \
	-H 'Content-Type: application/json' \
	"${JIRA_URL?}/rest/api/2/search?jql=$(:
		)assignee=currentuser()%20AND%20statusCategory!=Done" \
| jq -rc ".issues[] | [.key, .fields.status.statusCategory.name, $(:
	).fields.created, .fields.summary] | @tsv" \
| sed -e '1i\
'"$header
"

tabs -8
