#!/usr/bin/env python3
# Warning: this will fail in python 3.8, since the datetime
# module there will not recognize the format of the timestamp.
# vim: sw=8 ts=8 sts=8 noet

# Given a ticket (key or id), show the times in various states

from jira import JIRA, JIRAError
import os
import sys
from http import HTTPStatus
from datetime import datetime


jira_url = os.environ['JIRA_URL']
jira_token = os.environ['JIRA_TOKEN']
email = os.environ['EMAIL']

def main():
	jira = JIRA(jira_url, basic_auth=(email, jira_token))
	issue = jira.issue(sys.argv[1], expand='changelog')

	prev = datetime.fromisoformat(issue.changelog.histories[-1].created)

	for h in issue.changelog.histories[-2::-1]:
		for item in (i for i in h.items if i.field == 'status'):
			this = datetime.fromisoformat(h.created)
			duration = this - prev
			prev = this
			print(f'{str(duration):>30}  {item.fromString:>30}  {item.toString}')


try:
	main()
except KeyboardInterrupt:
	sys.exit(1)
except JIRAError as e:
	raise SystemExit(f'{e.status_code}: {HTTPStatus(e.status_code).phrase}')
