#!/bin/bash

# /issue/ID

test $# = 0 && set -- project

if test -n "$USE_BEARER_TOKEN"; then
	auth=(-H "Authorization: Bearer $JIRA_TOKEN")
else
	auth=(-u "${EMAIL?}:${JIRA_TOKEN?}")
fi

set -x
curl -Ssf \
	-H 'Content-Type: application/json' \
	"${auth[@]}" \
	${JIRA_URL?}/rest/api/2/"$1" \
| jq .
