#!/usr/bin/env python

from collections.abc import Sequence, Iterable
from abc import ABC, abstractmethod


# Example from https://docs.python.org/3.10/library/collections.abc.html#collections.abc.MutableMapping
class D:                                 # No inheritance
    def __init__(self): ...              # Extra method not required by the ABC
    def __getitem__(self, index):  ...   # Abstract method
    def __len__(self):  ...              # Abstract method
    def count(self, value): ...          # Mixin method
    def index(self, value): ...          # Mixin method

assert(not issubclass(D, Sequence))
Sequence.register(D)                     # Register instead of inherit
assert(issubclass(D, Sequence))
assert(isinstance(D(), Sequence))

# For simple interfaces, you do not have to explicitly register
class E:
    def __iter__(self): ...
    def __next__(next): ...

assert(issubclass(E, Iterable))
assert(isinstance(E(), Iterable))


class F(ABC):
    @abstractmethod
    def foo(self, x): ... # All subclasses must define

class G(F):
    def foo(self, y):
        return y;
g = G()


# This definition is fine, but instances cannot be instantiated
class H(F): pass
try:
    h = H()
    assert(False)
except TypeError as e:
    assert(True)
