#!/usr/bin/env python3

# Demonstrate any and all
import sys

x = [1, 3, 6, 9]

if any(a > 7 for a in x):
    assert(True)
else:
    assert(False)

if all(a > 7 for a in x):
    assert(False)
else:
    assert(True)

lod = []
lod.append({'a': 5})
lod.append({'b': 7})
lod.append({'a': 9})
if any(x.get('a', 0) == 7 for x in lod):
    assert(False)
