#!/usr/bin/env python

import sys
import os

print(f'len(sys.argv) = {len(sys.argv)}')

if len(sys.argv) == 1:
    sys.argv.append('foo')

if __name__ == '__main__':
    name = sys.argv[0]  # Path used to invoke the program
    print(f'argv[0] == {os.path.basename(name)}')
    print('  i:\tsys.argv[i]')
    print('-----------------')
    for i in range(len(sys.argv)):
        print(f'{i:3}:\t{sys.argv[i]}')
