#!/usr/bin/env python

import sys

print(f'len(sys.argv) = {len(sys.argv)}')

if __name__ == '__main__':
    print(f'argv[0] == {sys.argv[0]}')  # Path used to invoke the program
    print('  i:\tsys.argv[i]')
    print('-----------------')
    for i in range(len(sys.argv)):
        print(f'{i:3}:\t{sys.argv[i]}')
