#!/usr/bin/env python3

import os
import traceback
import sys

# Build module with -O to disable (eg, python -O $file)
print(f"debug = {__debug__}")  # Can be modified with -O

# Can also disable assertions like:
if len(sys.argv) > 1 and sys.argv[1] == 'nodebug':
    os.environ['PYTHONOPTIMIZE'] = '1'
    del sys.argv[1]
    python = sys.executable
    os.execl(python, python, *sys.argv)

# Assert will either "raise AssertionError" or
# raise "AssertionError(expression2)"

try:
    if len(sys.argv) > 1:
        assert False, sys.argv[1]
    else:
        assert False
except AssertionError as e:
    print("caught:", e.__repr__())
    print("caught:", e.__traceback__)
    print(dir(e.__traceback__))
    print(traceback.extract_tb(e.__traceback__))
    print(e)
else:
    print('No assertions raised')  #  Happens when -O is applied
