#!/usr/bin/env python2.7

import sys
import os
import time
import atexit
import threading
import signal

def bar(signum, frame):
    raise SystemExit

def foo():
    print "in foo"
    raise SystemExit(0)

def killer():
    time.sleep(1)
    os.kill(os.getpid(), signal.SIGTERM)

atexit.register(foo)
signal.signal(signal.SIGTERM, bar)
a = threading.Thread(target=killer)
a.start()
signal.pause()
a.join()
