#!/usr/bin/env python3

# Exercise
# Using a generator comprehension, define a generator for the series:

# (0, 2).. (1, 3).. (2, 4).. (4, 6).. (5, 7)


g = ( (a, a + 2) for a in range(0, 6) if a != 3 )
for i in g:  print(i)

