#!/usr/bin/env python

from io import StringIO
from collections import namedtuple

# Demonstrate parsing a csv with numeric values into named tuples

data = '''\
foo,bar,baz,qux
1,2,3,4
6,3,8,9
10,11,12,12
'''

def get_records():
    with StringIO(data) as s:
        headers = s.readline().strip().split(',')
        record = namedtuple('record', headers)
        for line in s.readlines():
            yield record(*map(float, line.strip().split(',')))

res = []
for x in get_records():
    res.append(x.bar)
assert(res == [2,3,11])
