#!/usr/bin/env python

# keywords: tput

# ansi_escapes is not in the standard library
from ansi_escapes import ansiEscapes
import time
import sys

print('Hello, World!', end='')

sys.stdout.flush()

# Move the cursor down two rows and to the right
# print(ansiEscapes.cursorDown(2) + ansiEscapes.cursorForward(), end='')
# Note that "down two rows" will not scroll the display, so
# if already at the bottom of the screen it is a no-op.

time.sleep(.25)

print(ansiEscapes.cursorBackward(20) +
    'Bye, World!' +
    ansiEscapes.eraseEndLine
)

# Now do the same thing simpler:
print('Hello, World', end='\r')
time.sleep(.25)
print('Bye, World! ')

'''
    cursorBackward(count=1)
    cursorDown(count=1)
    cursorForward(count=1)
    cursorMove(x, y=None)
    cursorTo(x, y=None)
    cursorUp(count=1)
    eraseLines(count)
    link(text, url)

DATA
    BEL = '\x07'
    ESC = '\x1b['
    OSC = '\x1b]'
    SEP = ';'
    beep = '\x07'
    clearScreen = '\x1bc'
    clearTerminal = '\x1b[2J\x1b[3J\x1b[H'
    cursorGetPosition = '\x1b[6n'
    cursorHide = '\x1b[?25l'
    cursorLeft = '\x1b[G'
    cursorNextLine = '\x1b[E'
    cursorPrevLine = '\x1b[F'
    cursorRestorePosition = '\x1b[u'
    cursorSavePosition = '\x1b[s'
    cursorShow = '\x1b[?25h'
    eraseDown = '\x1b[J'
    eraseEndLine = '\x1b[K'
    eraseLine = '\x1b[2K'
    eraseScreen = '\x1b[2J'
    eraseStartLine = '\x1b[1K'
    eraseUp = '\x1b[1J'
    iTerm = <ansi_escapes.ansi_escapes.ITerm object>
    isTerminalApp = False
    scrollDown = '\x1b[T'
    scrollUp = '\x1b[S'

'''
