#!/usr/bin/env python


from datetime import datetime, timedelta


a = datetime.fromisoformat('2021-07-02-21:35:05')

a += timedelta(hours=2)
a += timedelta(days=1)
print(a)

# b = datetime.strptime('Fri Mar 24 11:03:49 AM MDT 2023', '%a %b %d %H:%M:%S AM %Z %Y')
b = datetime.strptime('Sat Mar 24 11:03:49 AM MDT 2023', '%a %b %d %H:%M:%S %p %Z %Y')
print(b)
