#!/usr/bin/env python2.7


def baz(i):
    return 'baz', i

class foo(object):
    def __init__(self, arg):
        self.arg=arg
        print 'creating a foo with', arg

    def __call__(self, o):
        print 'my arg is', self.arg
        print 'my o is', o
        return baz



@foo(3)
def bar(arg):
    return baz


print 'calling bar'
k = bar(9)
print 'bar returned:', k


def wr2(func):
    def rv(arg):
        print "in wr2 rv"
        return func(arg) + 1
    return rv

def wr1(func):
    def rv(arg):
        print "in wr1 rv"
        return func(arg) + 3
    return rv

@wr2
@wr1
def sum(arg):
    return arg + 2

print sum(1)
