#!/usr/bin/env python

# See: https://docs.python.org/3/howto/descriptor.html

import datetime

class Foo:
    def __get__(self, obj, objtype = None):
        return datetime.datetime.now()


class Bar:
    n = Foo()


a = Bar()
print(a.n)
