#!/usr/bin/env python

# See: https://docs.python.org/3/howto/descriptor.html

# A descriptor is any object that defines __get__(), __set__(), or __delete__()

import datetime

class Foo:
    def __get__(self, obj, objtype = None):
        print(f'objtype = {objtype}')
        return datetime.datetime.now()


class Bar:
    n = Foo()


a = Bar()
print(a.n)  # objtype = <class '__main__.Bar'>
