#!/usr/bin/env python

import types
import json

class dqdict(dict):
    def __str__(self):
        return json.dumps(self)

a = dqdict()
a['foo'] = 'bar'
a[3] = 'aux'
assert str(a) == '{"foo": "bar", "3": "aux"}'

def mutate(a):
    '''Dictionaries are passed by reference.  This mutates in the caller.'''
    a['foo'] += 5

b = {'foo':-4}
mutate( b )       # value increments
mutate( dict(b) ) # To avoid mutation, pass a copy
b['bar'] = 1
b['baz'] = 2
b['bar'] = 2  # Does not change insertion order
del b['bar']  # But deleting and re-assigning does change order
b['bar'] = 3
expect = { 'foo': 1, 'baz': 2, 'bar': 3 }
assert b == expect

# Iterate over a dictionary.  Keys are returned in insertion order.
for k, v in b.items():
    assert v == expect[k]

for k in b.keys():
    assert b[k] == expect[k]

for v in b.values():
    pass



def slice_a_dict():
    print("Demonstrate slicing a dictionay")
    a = {'foo': 1, 'bar': 2, 'baz': 3}
    keys = ['foo', 'baz']
    print(f'a = {a}');
    s = { k:a[k] for k in keys if k in a }
    print(f'slice = {s}')

slice_a_dict()

a = { 'a': 1, 'b': 2}
assert {'a': 5, 'b': 2} == a | { 'a':  5}  # | == "dictionary union operator"
assert {'a':1, 'b':3, 'c':0} == a | {'b':3, 'c':0}


a = types.SimpleNamespace({'foo': 3})
a.bar = 5
assert a.foo == 3
assert a.bar == 5
b = types.SimpleNamespace(foo=3)
b.bar = 5
assert b.foo == 3
assert b.bar == 5
