#!/usr/bin/env python

# Demonstrate that __truediv__ is the method that implements the / operator

class foo():
	def __init__(self, x=0):
		self.x = x

	def __truediv__(self, other):
		return self.x / other.x

a = foo(3)
b = foo(5)
assert a/b == 3/5
assert b/a == 5/3
