#!/usr/bin/env python

import sys
import os
class foo(Exception):
    pass

try:
	raise foo ("help")
except Exception as e:
    print "Raised", e
    sys.stderr.write("{}: cannot write {}/{}: {}\n".format(
        os.path.basename(sys.argv[0]), "foo", "bar", e))


try:
    f = open('/non/extant/file', 'r')
except IOError as e:
    sys.stderr.write("{}: {}: {}\n".format(
        os.path.basename(sys.argv[0]), e.filename, e.strerror))
    raise SystemExit("{}: {}: {}".format(
        os.path.basename(sys.argv[0]), e.filename, e.strerror))
except Exception as e:
    raise SystemExit("{}: {}".format(
        os.path.basename(sys.argv[0]), e))
