#!/usr/bin/env python

import sys

with open(sys.argv[0]) as f:
	for x in f.readlines():  # readlines is NOT an iterator; returns a list
		assert(x.startswith('#!/usr/bin'))
		break

with open(sys.argv[0]) as f:
	for x in f:  # f acts as a proper iterator
		assert(x.startswith('#!/usr/bin'))
		break
