#!/usr/bin/env python

import sys

try: top = int(sys.argv[1])
except IndexError: top = 3

for x in range(5):
	if x == top:
		break
	print(x)
else:
	print("The 'else' branch is only executed if the loop terminates without break")


# Iterate if foo may be None or otherwise Falsey
foo = (1, 2, 3)
for x in (foo or ()): pass
# Do not use "foo or []", since that creates a temporary mutable
