#!/usr/bin/env python

import sys

try: top = sys.argv[1]
except IndexError: top = 3

for x in range(5):
	if x == top:
		break
	print(x)
else:
	print("The 'else' branch is only executed if the loop terminates without break")
