#!/usr/bin/env python

import itertools

def foo():
	while True:
		yield 0
		yield 0
		yield 1
		yield 1

x = foo()
m = [next(x) for _ in xrange(9)]
k = itertools.islice(foo(), 9)
print( "m = {}", m)

# a = k[0:9]
# print( "a = {}", a)
