#!/usr/bin/env python

# Trivial demonstration of __getitem__, __setitem__
class Foo():
    def __init__(self, d):
        self.cache = d

    def __getitem__(self, key):
        return self.cache[key]

    def __setitem__(self, key, value):
        self.cache[key] = value


a = Foo({5: 1})

print(a[5])

a['foo'] = 'bar'
print(a['foo'])

