#!/usr/bin/env python

# Simple example of an http server

from http.server import BaseHTTPRequestHandler
import http.server
import socketserver
import string
import random
import io
import json

PORT = 8001

class Data_generator(http.server.BaseHTTPRequestHandler):
    def do_GET(self):
        self.send_response(200)
        self.send_header("Content-Type", 'application/octet-stream')
        response_data = b'data'
        self.send_header("Content-Length", str(len(response_data)))
        self.end_headers()
        self.wfile.write(response_data)

with socketserver.TCPServer(("", PORT), Data_generator) as httpd:
    httpd.serve_forever()
