#!/usr/bin/env python

import sys
import errno

if sys.stdout.isatty():
    raise SystemExit("You should pipe this to head; do not write to a tty")

while True:
    try:
        sys.stdout.write("Hello, world!\n")
        sys.stdout.flush()
    except IOError as e:
        if e.errno == errno.EPIPE:
            raise SystemExit(e)
        else:
            raise e
