#!/usr/bin/env python2.7

import sys

while True:
    try:
        sys.stdout.write("Hello, world!")
    except IOError as e:
        if e.errno == 32:  # Broken pipe
            raise SystemExit(e)
        else:
            raise e
