#!/usr/bin/env python

from jinja2 import Environment, FileSystemLoader
import os
import sys

sample_input = '''
Simple substituion: {{ DB_USER }}
literal_bracket: {{ '{{' }}
raw: {% raw -%}
    This text is not {{ expanded }} at all!
    And, by virtue of the "-", all leading whitespace is removed.
{% endraw %}
"data": {
        "name": "example template",
        "comments": "demonstrate{#
                #} commenting out whitespace{#
                #}",
        "unset becomes blank": "{{kafka_truststore_password}}"
}
{% for i in alist %}
    item {{ i }}
{% endfor %}

join-sample: {{ names | join(',') }}
join-append-sample: {{ names | join(':' + (port | string) + ',') +
        ":" + (port|string)}}
'''

def main(pathlist=None):
    if pathlist:
        for path in pathlist:
            with open(path, 'r') as f:
                render_string(f.read())
    else:
        render_string(sample_input)

def render_string(data):

    env = Environment(trim_blocks=True)
    template = env.from_string(data)
    render_data = template.render(
        title='title',
        alist=(1,2,3),
        port = 3764,
        names = [ 'name1', 'name2', 'name3' ],
        DB_USER=os.environ.get('USER')
    )
    print render_data

if __name__ == '__main__':
    main(sys.argv[1:])
