#!/usr/bin/env python

from jinja2 import Environment, FileSystemLoader
import os

def main(path=None):
    if path:
        with open(path, 'r') as f:
            data = f.read()
    else:
        data = '''
{
    "name": "{{ DB_USER }}"
    "data": {
        "name": "example template",
        "comments": "{#
                #}demonstrate commenting out whitespace{#
                #}",
        "unset becomes blank": "{{kafka_truststore_password}}"
    }
    {% for i in alist %}
        item {{ i }}
    {% endfor %}
}
'''

    env = Environment(trim_blocks=True)
    template = env.from_string(data)
    render_data = template.render(
        title='title',
        alist=(1,2,3),
        DB_USER=os.environ.get('USER')
    )
    print render_data

if __name__ == '__main__':
    main()
