#!/usr/bin/env python

import logging
import os
import sys


logger = logging.getLogger()
logger.setLevel(os.environ.get('LOGLEVEL', 'warning').upper())

# Without handlers, every message has "LEVEL:name:" prepended
# With these handler, there is no prefix.
if os.environ.get('WITH_HANDLERS'):
    stderr_handler = logging.StreamHandler()
    stderr_handler.setLevel(logging.WARNING)

    stdout_handler = logging.StreamHandler(sys.stdout)
    stdout_handler.addFilter(lambda r: r.levelno < logging.WARNING)

    logger.addHandler(stderr_handler)
    logger.addHandler(stdout_handler)


class Foo(Exception): pass

try:
    raise Foo('oops')
except:
    logging.debug('test debug')
    logger.info('test info to logger')
    logging.info('test info to logging')
    logging.warning('test warning')
    logging.error('test error')
    logging.fatal('*' * 20 + 'This fatal includes stack trace', exc_info=1)
    logging.critical('test critical (no stacktrace)')
    logging.critical('test critical (w/stacktrace)', exc_info=1)
    logging.exception('test expcetion (includes stack trace)')
    logging.exception('test expcetion (no stack trace)', exc_info=0)
