#!/usr/bin/env python

import logging
import os
import sys


logging.basicConfig(level=os.environ.get('LOGLEVEL', 'warning').upper())
logger = logging.getLogger()
stdout_handler = logging.StreamHandler(sys.stdout)
stdout_handler.addFilter(lambda r: r.levelno < logging.WARNING)
logger.addHandler(stdout_handler)
logger.handlers[0].setLevel(logging.WARNING)



class Foo(Exception): pass

try:
    raise Foo('oops')
except:
    logging.debug('test debug')
    logging.info('test info')
    logging.info('test logging.info to logging')
    logging.warning('test warning')
    logging.error('test error')
    logging.fatal('*' * 20 + 'This fatal includes stack trace', exc_info=1)
    logging.critical('test critical (no stacktrace)')
    logging.critical('test critical (w/stacktrace)', exc_info=1)
    logging.exception('test expcetion (includes stack trace)')
    logging.exception('test expcetion (no stack trace)', exc_info=0)
