#!/usr/bin/env python

import pathlib
import sys

# pathlib should generally be preferred over os.path

names = sys.argv[1:] if len(sys.argv) > 1 else ['/', 'tmp', 'foo']

f = pathlib.Path(*names)
full_name = f.absolute()

print(full_name, end=' ')
print('exists' if f.exists() else 'does not exist')

a = pathlib.Path('/') / 'foo' / 'bar'
assert(str(a.parent) == '/foo')
