#!/usr/bin/env python

import pathlib
import sys

# pathlib should generally be preferred over os.path

names = sys.argv[1:] if len(sys.argv) > 1 else ['/', 'tmp', 'foo']


# check if a file exists
f = pathlib.Path(*names)
full_name = f.absolute()

print(full_name, end=' ')
print('exists' if f.exists() else 'does not exist')

print(f' f = {f}, f.parent = {f.parent}')
