#!/usr/bin/env python

# New in 3.10

# See:
#    PEP 634: https://peps.python.org/pep-0634/
#    https://docs.python.org/3/reference/compound_stmts.html#match

import sys
from enum import Enum

if sys.version_info < (3, 10):
    raise SystemExit(f'Pattern match only valid in 3.10.  You are running {sys.version.split(" ")[0]}')

import pattern_matching

pattern_matching.main()

