#!/usr/bin/env python

from io import BytesIO
from pypdf import PdfReader, PdfWriter
from pypdf.annotations import FreeText
from reportlab.pdfgen import canvas
import sys

input_file = "file1.pdf" if len(sys.argv) < 2 else sys.argv[1]
output_file = "output.pdf" if len(sys.argv) < 3 else sys.argv[2]

# Create an overlay PDF with visible text
packet = BytesIO()
can = canvas.Canvas(packet)
can.setFont("Helvetica-BoldOblique", 14)
can.setFillColorRGB(0, 0, 0)  # black
can.drawString(25, 600, "Hello World!")
can.drawString(25, 580, "This is a new line.")
can.save()
packet.seek(0)

# Merge overlay onto first page
overlay = PdfReader(packet)

writer = PdfWriter()
reader = PdfReader(input_file)

for i, page in enumerate(reader.pages):
    if i == 0:
        page.merge_page(overlay.pages[0])
    writer.add_page(page)


with open(output_file, "wb") as f:
    writer.write(f)
