#!/usr/bin/env python

# Simple example using queue
import threading
import queue
import random
import time

a = queue.Queue(maxsize=5)
# methods: qsize, empty, full, put, put_nowait, get, get_nowait, task_done, join

def worker(name):
    while True:
        i = a.get()
        print(f'{name} working on {i}: size = {a.qsize()}')
        time.sleep(random.uniform(.1,.5))
        a.task_done()

threading.Thread(target=worker, args=('foo',), daemon=True).start()
threading.Thread(target=worker, args=('bar',), daemon=True).start()

block_count = 0
for i in range(15):
    should_block = block_count < 5
    try:
        a.put(i, block=not should_block)
    except queue.Full:
        try:
            a.put(i, timeout=random.uniform(0,.1))
        except:
            print(f"blocked inserting {i}")
            block_count += 1
            a.put(i)

    # put_nowait is the same as put(item, block=False)

a.join()
