#!/usr/bin/env python

import urllib.request

import sys
if len(sys.argv) > 1:
    port = int(sys.argv[1])
else:
    port = 8001

url = f'http://localhost:{port}'

try:
    with urllib.request.urlopen(url) as response:
        data = response.read()
        print(data.decode('utf-8'))
except urllib.error.URLError as e:
    print(f"Error opening URL: {e}")
except urllib.error.HTTPError as e:
    print(f"HTTP error: {e.code} - {e.reason}")
