#!/usr/bin/env python2.7

import threading
import os
import sys
import time
import signal

class Foo(Exception): pass

def foo(name, i):
    while i > 0:
        print i
        i -=1
        time.sleep(1)

def shutdown(signum, frame):
    print 'Shutting down with', signum
    sys.stdout.flush()

print 'pid:', os.getpid()

a = threading.Thread(target=foo, args=('', 10))


signal.signal(signal.SIGTERM, shutdown)
os.kill(os.getpid(), signal.SIGTERM)
os.kill(os.getpid(), signal.SIGTERM)
a.start()
#if we a.join(), it is uninterruptible!
while True:
    time.sleep(1)
    if not a.is_alive():
        raise SystemExit(0)
