#!/usr/bin/env python

from operator import itemgetter

# Sort tuple by index 2
student_tuples = [
    ('john', 'A', 15),
    ('jane', 'B', 12),
    ('dave', 'B', 10),
]

# sort by .[2]
a = sorted(student_tuples, key=lambda student: student[2])
print('sorted by age:')
for x in a: print(x)

# sort by .[1], then by .[2]
a = sorted(student_tuples, key=itemgetter(1,2))
print('sorted by grade, then age:')
for x in a: print(x)
