#!/usr/bin/env python

import threading
import time
import random
from datetime import datetime

val=0
message=None

def show_status():
    global val
    global message
    spinner = '-\|/'
    idx = 0

    while True:
        time.sleep(.25)
        m = datetime.now().strftime(f'%c.%f {spinner[idx]}')
        end = f'\033[K\r'
        idx = (idx+1) % 4
        if message:
            print(f'{m}: {message}', end=end, flush=True)
        else:
            print(f'{m}: val = {val}', end=end, flush=True)

a = threading.Thread(target=show_status)
a.daemon = True
a.start()

while True:
    val
    a = random.choice([.12, .37, .45, .65, 1, 5])
    if a == 5:
        message = "sleeping for 5!"
    else:
        val += a
        message = None
    time.sleep(a)
