#!/usr/bin/env python
# Compute mean, median, and std deviation of the input

import statistics
import sys


print("mean\tmedian\tstddev\tdata")
for x in sys.stdin:
    v = []

    for y in map(float, x.split()):
        v.append(y)

    v.sort()
    print("{}\t{}\t{}\t{}".format(statistics.mean(v), statistics.median(v), statistics.pstdev(v), v))
