#!/usr/bin/env python

# keyword: file-like object, iostream, streamio, iostring, stringio

from io import StringIO, SEEK_END

with StringIO("hello, ") as a:
    a.seek(0, SEEK_END)
    a.write('world')
    hw = a.getvalue()
assert(hw == 'hello, world')

s = "Hello, world!"
b = StringIO(s)
assert(b.read() == 'Hello, world!')


def exhaust(a, b):
    with open(a, 'rb') if a else b as f:
        print(f.read())


with StringIO("foo") as b:
    exhaust(None, b)
    # b.seek(0)  # Would fail, since exhaust() closes file
    # print(b.read())  # Also would fail
