#!/usr/bin/env python

s = [
	f'{"centered":^15}',
	f'{"left":<15}',
	f'{"right":>15}',
	f'{"neither justified or truncated":>15}',
	f'{"truncated to 15":15.15}',
	f'{"Truncated to 4 characters, centered on width of 20":^20.4}',
]
for i in s:
	print(f':{i}:')
