#!/usr/bin/env python


class Base:
	def __init__(self, name, x, y=3):
		self.name = name
		self.x = x
		self.y = y

	def __repr__(self):
		return f'{self.name}.x = {self.x}, {self.name}.y = {self.y}'

class Derived(Base):
	def __init__(self, *args, **kwargs):
		super().__init__(*args, **kwargs);


a = Derived('foo', 2, y=17)
print(a)
