#!/usr/bin/env python

# miscellaneous things found in sys

import sys

print(sys.version_info)        # sys.version_info(major=x, minor=x, micro=x, releaselevel='final', serial=0)
print(type(sys.version_info))  # type is sys.version_info


'''
In 3.11.2, dir(sys) gives
[
'__breakpointhook__',         '__displayhook__',                      '__doc__',              '__excepthook__',
'__interactivehook__',        '__loader__',                           '__name__',             '__package__',
'__spec__',                   '__stderr__',                           '__stdin__',            '__stdout__',
'__unraisablehook__',         '_base_executable',                     '_clear_type_cache',    '_current_exceptions',
'_current_frames',            '_debugmallocstats',                    '_framework',           '_getframe',
'_getquickenedcount',         '_git',                                 '_home',                '_stdlib_dir',
'_xoptions',                  'abiflags',                             'addaudithook',         'api_version',
'argv',                       'audit',                                'base_exec_prefix',     'base_prefix',
'breakpointhook',             'builtin_module_names',                 'byteorder',            'call_tracing',
'copyright',                  'displayhook',                          'dont_write_bytecode',  'exc_info',
'excepthook',                 'exception',                            'exec_prefix',          'executable',
'exit',                       'flags',                                'float_info',           'float_repr_style',
'get_asyncgen_hooks',         'get_coroutine_origin_tracking_depth',
'get_int_max_str_digits',     'getallocatedblocks',                   'getdefaultencoding',   'getdlopenflags',
'getfilesystemencodeerrors',  'getfilesystemencoding',                'getprofile',           'getrecursionlimit',
'getrefcount',                'getsizeof',                            'getswitchinterval',    'gettrace',
'hash_info',                  'hexversion',                           'implementation',       'int_info',
'intern',                     'is_finalizing',                        'maxsize',              'maxunicode',
'meta_path',                  'modules',                              'orig_argv',            'path',
'path_hooks',                 'path_importer_cache',                  'platform',             'platlibdir',
'prefix',                     'ps1',                                  'ps2',                  'pycache_prefix',
'set_asyncgen_hooks',         'set_coroutine_origin_tracking_depth',
'set_int_max_str_digits',     'setdlopenflags',                       'setprofile',
'setrecursionlimit',          'setswitchinterval',                    'settrace',             'stderr',
'stdin',                      'stdlib_module_names',                  'stdout',               'thread_info',
'unraisablehook',             'version',                              'version_info',         'warnoptions'
]
'''
