#!/usr/bin/env python3

import tempfile

# the temp diretory and all contents are unlinked
# when the context manager exits
with tempfile.TemporaryDirectory() as t:
	print(f't = {t}')

o = tempfile.TemporaryFile()

o.write(b'foo')
o.seek(0)
print(o.read())
