#!/usr/bin/env python

# Keyword: tr
# Simple example using a translation table to delete characters from a string

a = 'The quick brown fox jumps over the lazy dog'

# Remove all q, j, a, and z
b = a.translate(''.maketrans('', '', 'qjaz'))

print(f'a = {a}')
print(f'b = {b}')


#  [ins] In [1]: help(''.maketrans)
#  Help on built-in function maketrans:
#
#  maketrans(...)
#      Return a translation table usable for str.translate().
#
#      If there is only one argument, it must be a dictionary mapping Unicode
#      ordinals (integers) or characters to Unicode ordinals, strings or None.
#      Character keys will be then converted to ordinals.
#      If there are two arguments, they must be strings of equal length, and
#      in the resulting dictionary, each character in x will be mapped to the
#      character at the same position in y. If there is a third argument, it
#      must be a string, whose characters will be mapped to None in the result.
