#!/usr/bin/env python

# Keyword: tr
# Simple example using a translation table to delete characters from a string

a = 'The quick brown fox jumps over the lazy dog'

m = ''.maketrans('', '', 'qjaz')   # Remove all q, j, a, and z
assert a.translate(m) == 'The uick brown fox umps over the ly dog'

m = ''.maketrans('T', 'X')         #  T -> X
assert a.translate(m).startswith('Xhe')

m = ''.maketrans({'h': 'x'})       #  h -> x
assert a.translate(m).startswith('Txe')


#  [ins] In [1]: help(''.maketrans)
#  Help on built-in function maketrans:
#
#  maketrans(...)
#      Return a translation table usable for str.translate().
#
#      If there is only one argument, it must be a dictionary mapping Unicode
#      ordinals (integers) or characters to Unicode ordinals, strings or None.
#      Character keys will be then converted to ordinals.
#      If there are two arguments, they must be strings of equal length, and
#      in the resulting dictionary, each character in x will be mapped to the
#      character at the same position in y. If there is a third argument, it
#      must be a string, whose characters will be mapped to None in the result.
