#!/usr/bin/env python

# keywords: annotation

# See: https://peps.python.org/pep-0484 and
# https://peps.python.org/pep-0649
# https://peps.python.org/pep-0695

# Verify the hints with 'mypy $path'

from __future__ import annotations  # Allow incomplete types (only necessary in 3.7-3.10)

# explicit import of types seems unnecessary when using
# __future__.annotations, but mypy requires it
from typing import Dict, Iterable, Tuple, Optional


def f(x: int, y: Optional[Iterable[Tuple[int, str]]] = None) -> Optional[int]:
    if x > 0:
        return x
    else:
        return None

class Bar():
    def __init__(self: Bar, x: Optional[int] = None) -> None:
        self.x = x

def g(x: Dict[str, int]) -> int:
    return x.get('foo', 2)

a: Bar = Bar(f(1))
b: int = 6
assert( 1 == g({'foo': 1}))

def annotated_function[T](a: T, b: T) -> T:
    pass
