#!/usr/bin/env python

# keywords: operator *, operator **, splat, spread, flatten, iterable unpacking
#     dictionary unpacking
# See https://docs.python.org/3/reference/expressions.html#expression-lists


# The operator * applies to an iterable, and unpacks it.  eg

t = (1, 2, 3, 4)
list_containing_tuple = [2, 3, t] # [2, 3, (1, 2, 3, 4)]
flattened_list = [2, 3, *t]       # [2, 3, 1, 2, 3, 4]

# The operator ** applies to a mapping
m = {'one': 1, 'two': 2}
b = {'zero': 0, **m}  # {'zero': 0, 'one': 1, 'two': 2}
# b = {0:'zero', *a}  # syntax error

# Override values by placing them after
b = {**m, 'two': 3}
assert(b['one'] == 1)
assert(b['two'] == 3)


# Commonly used to unpack into function arguments
def printer(*args, **kwargs):
    print(f'args = {args}')
    print(f'kwargs = {kwargs}')

printer(b)  # args = ({'zero': 0, 'one': 1, 'two': 2},), kwargs = {}
printer(*b)  # args = ('zero', 'one', 'two'), kwargs = {}
printer(**b)  # args = (), kwargs = {'zero': 0, 'one': 1, 'two': 2}

# Demonstrate amending created dict
def make_dict(foo, bar, **kwargs):
    return {'foo':foo, 'bar':bar, **kwargs}
assert make_dict(5, 3) == {'bar': 3, 'foo':5}
assert make_dict(5, 3, blah=6) == {'foo':5, 'bar': 3, 'blah': 6}

# A literal works as well:
assert({'a':1, ** {'a':2, 'b': 3}} == {'a':2, 'b': 3})
