#!/usr/bin/env python

import multiprocessing as mp


def foo(*args, **kwargs):
	print 'foo called with', args, 'and', kwargs

a = mp.Process(target=foo, args=(1,2,3), kwargs={'foo':5})
a.start()
a.join()

