#!/bin/sh

# Generate copy-pastable mysql commands.  Pass a db name as first argument
# to add where clauses.

where="${1:+WHERE table_schema = \"$1\"}"

cat << EOF
# Approximate the size of a tables in a db
SELECT table_name AS 'Table',
	round(((data_length + index_length) / 1024 / 1024), 2) as 'Size in MB'
	FROM information_schema.TABLES${where:+ $where};

# Get the number of rows of a tables in a db
SELECT table_name as 'Table', table_schema, TABLE_ROWS as 'Rows'
	FROM information_schema.tables${where:+ $where};

# Get the total size of a db
SELECT table_schema AS "Database",
	ROUND(SUM(data_length + index_length) / 1024 / 1024, 2) AS "Size (MB)"
	FROM information_schema.TABLES${where:+
	$where}
	GROUP BY table_schema;
