#!/bin/sh
# A random collection of symbols.

for i in \
	f09f9b91      $(: A stop sign: 🛑    )\
	e29c8b        $(: A yellow hand  ✋   )\
	f09f8cb9      $(: A rose 🌹          )\
; do
	printf "%8s:" "$i"
	printf "$i" | perl -nE 'say pack "H*", $_'
done
