#!/bin/sh

# API at https://developer.statuspage.io
#   /pages                       list all pages
#       /pages/$id/
#           /components          list components for a page
#           /subscribers         list subscribers for a page
#   /incidents                   list all incidents

curl -Ssf -X GET \
	-H "Authorization:OAuth $STATUSPAGE_KEY" \
	"https://api.statuspage.io/v1/${1-pages/$STATUSPAGE_PAGE/incidents}"
