#!/usr/bin/env perl
use 5.12.0;

# Put each word into an array indexed by first letter of the word.

my $sorted_words_by_first_letter;
my @words = qw/ banana apple astronaut yoyo buttons /;
my %keys;

foreach my $word (@words) {

	# find the first character
	$word =~ m/^(.)/;

	# put it at the end of the array for the appropriate letter
	push @{ $sorted_words_by_first_letter->{$1} }, $word;
	$keys{$1} = 1;
}


foreach my $k (keys %keys) {
	say "$k: ", join ',', @{ $sorted_words_by_first_letter->{$k} };
}
