#!/usr/bin/env perl
use 5.12.0;

my @n = ("foo", "bar", "baz");
my $arrayref = [];

$arrayref->[0] = "first entry";
my @b = @$arrayref;  # Copy the array
push @$arrayref, "2nd entry";

say "size of array is " . @n;
foreach my $v (@n) { say $v }

say "size of b array is " . @b;
foreach my $v (@b) { say $v }

say "size of arrayref is " . @$arrayref;
foreach my $v (@$arrayref) { say $v }


foreach my $v (@ARGV) { say "arg:", $v }

__DATA__

# Read entire input into a single array and sort it numerically
printf '1\n10\n15\n2\n' | perl -0777 -aE 'say foreach sort { $a <=> $b } @F'

# Generate the first few fibonacci numbers
perl -E 'my @b; push @b, 1; push @b, 1; foreach $n (1..50){ push @b, $b[@b-1] + $b[@b-2]};
    say join("\n", @b)' | nl -ba
