#!/usr/bin/env perl
use 5.12.0;

# Put each word into an array indexed by first letter of the word.

my $sorted_words_by_first_letter;
my @words = qw/ banana apple astronaut yoyo buttons /;

foreach my $word (@words) {

	# find the first character
	$word =~ m/^(.)/;

	# put it at the end of the array for the appropriate letter
	push @{ $sorted_words_by_first_letter->{$1} }, $word;
}


foreach my $k( keys %$sorted_words_by_first_letter ){
	say "$k: ", join ',', @{ $sorted_words_by_first_letter->{$k} };
}

say "a: ", join ',', @{ $sorted_words_by_first_letter->{'a'} };

# Use an anonymous array ref when the entry is not in the hash
say "m: ", join ',',  @{ $sorted_words_by_first_letter->{'m'} // [] };
