#!/usr/bin/env perl
use 5.12.0;

my @n = ("foo", "bar", "baz");
my $arrayref = [];

$arrayref->[0] = "first entry";

say "size of array is " . @n;
foreach my $v (@n) { say $v }

say "size of array isref " . @$arrayref;
foreach my $v (@$arrayref) { say $v }


foreach my $v (@ARGV) { say "arg:", $v }
