#!/usr/bin/env perl

use 5.12.0;
use warnings;

my $rv = 0;
sub fail {
	my ($msg) = @_;
	s/^\s+|\s+$//g; # Trim whitespace
	printf STDERR "%-25s %4d:$ARGV %s\n", $msg, $., $_;
	$rv = 1;
}

# naive scanning of c for style violations
while(<>) {
	fail 'Trailing whitespace' if( m/\s\n/m );
	foreach my $x ("if", "for", "while") {
		fail "space between $x and (" if( m/\W$x \(/ );
		fail "no space after $x(" if( m/\W$x\([^ \n]/ );
	}
	fail 'Bad indent' unless( m/^\t*[\S]/ or m/^$/ or m/^ \*/ );
} continue {
	close ARGV if eof;  #  Reset line numbering
}

exit $rv
