#!/usr/bin/env perl
use Math::Combinatorics;

my @n = qw(a b c);
my $combinat = Math::Combinatorics->new(
	count => 2,
	data => [@n],
);

print "combinations of 2 from: ".join(" ",@n)."\n";
print "------------------------".("--" x scalar(@n))."\n";
while(my @combo = $combinat->next_combination){
  print join(' ', @combo)."\n";
}

print "\n";

print "permutations of 3 from: ".join(" ",@n)."\n";
print "------------------------".("--" x scalar(@n))."\n";
while(my @permu = $combinat->next_permutation){
  print join(' ', @permu)."\n";
}

