#!/usr/bin/env perl

# At runtime, import all environment variables as perl vars with
# perl -Menv
# eg: perl -MEnv -E 'say $HOME'

use 5.12.0; # enables strict and warnings

my $c = $ENV{"FOO"} || "";

say "FOO = ", $c ? $c : "unset";
while( my ($k, $v) = each %ENV ){
	say "$k = $v";
}
