#!/usr/bin/env perl

# For details: perldoc perlform
# keywords: perlform template
use 5.12.0;

my $name = 'name';
my $login = 'login';
my $office = 'office';
my $uid = 32;
my $gid = 17;
my $home = 'home';

format =
@<<<<<<<<<<<<<<<<<< @||||||| @<<<<<<@>>>> @>>>> @<<<<<<<<<<<<<<<<<
$name,              $login,  $office,$uid,$gid, $home
.

write;
