#!/usr/bin/env perl

# perldoc -f  each
# perldoc perlref
# perldoc perldsc

use 5.12.0;
use warnings;

my $hashref = {}; # $hashref is a reference to an anonymous hash
my %hash = ( 'foo' => 'bar' );
$hash{"baz"} = "qux";

say "hashref: ", $hashref; # eg "hashref: HASH(0x7f8e4480bc10)"
say "hash: ", %hash;       # eg "hash: foobarbazqux"
say "hashref is a ref to ", ref($hashref); # hashref is a ref to HASH

foreach my $x ( 1 .. 5 ) {
	$hash{$x} = $x;            # Add entry to %hash
	$hashref->{$x + 10} = $x;  # Add entry to $hashref
}
# Shows buckets used/allocated
print "buckets allocated for hash:". scalar(%hash) . "\n";
print "buckets allocated for hashref:" . scalar(%$hashref) . "\n";

foreach my $k( keys %hash ){
	print "key = $k, value = $hash{$k}\n";
}
foreach my $k( keys %{ $hashref }){
	print "key = $k, value = $hashref->{$k}\n";
}
print "Iterate with each\n";
while( my ($k, $v) = each %$hashref ){
	print "key = $k, value = $v\n";
}
while( my ($k, $v) = each %$hashref ){
	say $k, '->', $hashref->{$k};
	delete $hashref->{$k};   # This is safe
}
