#!/usr/bin/env perl

# perldoc -f  each
# perldoc perldsc

use 5.12.0;
use warnings;

my $hashref = {}; # $hashref is a reference to an anonymous hash
my %hash = ( 'foo' => 'bar' );
$hash{"baz"} = "qux";

foreach my $x ( 1 .. 5 ) {
	$hash{$x} = $x;            # Add entry to %hash
	$hashref->{$x + 10} = $x;  # Add entry to $hashref
}
# Shows buckets used/allocated
print "buckets allocated for hash:". scalar(%hash) . "\n";
print "buckets allocated for hashref:" . scalar(%$hashref) . "\n";

foreach my $k( keys %hash ){
	print "key = $k, value = $hash{$k}\n";
}
foreach my $k( keys %{ $hashref }){
	print "key = $k, value = $hashref->{$k}\n";
}
while( my ($k, $v) = each %$hashref ){
	say $k, '->', $hashref->{$k};
	delete $hashref->{$k};   # This is safe
}
