#!/usr/bin/env perl

use 5.12.0; # enables strict and warnings

# use Time::Format qw/%time/;
use Time::HiRes qw/gettimeofday/;

my $time = gettimeofday; # Returns ssssssssss.uuuuuu in scalar context
say $time;

# print qq|$time{'yyyymmdd hh:mm:ss.mmm', $time}\n|;
