#!/usr/bin/env perl
#
# Prepend "Hello, " to each line of input and write it.
use v5.14; # enables warnings
use Inline 'C';

while(<>) {
	my $k = myfunc ('Hello, ', $_);
	print "$k";
}

__END__
__C__

SV* myfunc( const char *a, const char *b ) {
       return newSVpvf("%s%s", a, b);
}
