#!/usr/bin/env perl

use 5.10.0;
use strict;
use warnings;

undef $/;
my $str = <DATA>;
my @array = $str =~ /( \{ (?: [^{}]* | (?0) )* \} )/xg;

say join "\n" => @array;

__DATA__
squiggled {{ double { one }  }}

This {{estimate}}, {{but}} realize
random {{nested {{probably}} take}}.  {{Namely}}, I'm
single { one }
Unmatched { not closed
