#!/usr/bin/env perl

# Here's a way to through data at a sink:
# yes | nl | perl -e 'STDOUT->blocking(0);print while(<>);' | ncat -kl localhost 1987

use strict;
use warnings;

STDOUT->blocking(0);
while(<>) {
	print;
}
