#!/usr/bin/env perl

use strict;
use warnings;

my $v = 0;
$SIG{'PIPE'} = sub { print STDERR "Caught a PIPE" };

my $p;
STDERR->blocking(0);
do {
	$p = <STDIN>;
	$v++;
} while(print $p);

print STDERR "failed after $v\n";

