#!/usr/bin/env perl

use strict;
use warnings;

open my $fh, '<', $ARGV[0] or die "$ARGV[0]:$!\n"; # Newline suppresses extra ...
# diagnostics.  Without the newline, the line number in the script will be printed.

while(<$fh>) {
	print $_;
}

