#!/usr/bin/env perl

use 5.12.0;

# Print a random value from a list or a string
if( @ARGV == 0) {
	# Select random element from a list
	my @s = ('a'..'z','0'..'9');
	say $s[rand @s];
} else {
	# Select random char from a string
	foreach my $arg (@ARGV) {
		say substr ($arg, rand length $arg, 1)
	}
}


__DATA__
# print a string of random lower case letter with lenth 10
$ perl -le 'print map { (q(a)..q(z))[rand(26)] } 1 .. 10'

# print a string of random hex digits with random length between 8 and 12
$ perl -le 'print map { sprintf q|%X|, rand(16) } 1 .. rand(5) + 8'

# Generate an md5sum of a file
$ perl -MDigest::MD5=md5_hex -le 'print md5_hex(qq|@ARGV|)' foo
