#!/usr/bin/env perl


use 5.12.0;

my $path = shift;
opendir my $dir, $path or die "can't opendir $path: $!";

for my $name ( grep { /^example_/ && -f "$path/$_" } readdir($dir) ){
        rename("$path/$name", "$path/" . substr ($name, 8) ) || die "$!: $name";
}
