#!/usr/bin/env perl

use strict;
use warnings;

my $c = $ENV{'COLS'} // $ENV{'COLUMNS'};
my $r = $ENV{'ROWS'} // $ENV{'LINES'};
sub draw_horizontal {
	my $i = 0;
	while( $i < $c ) {
		printf "%s", ($i % 10) ? ($i % 10) : "|";
		$i += 1;
	}
}
draw_horizontal();
my $i = 1;
while( $i < $r - 2 ) {
	my $len = 10;
	my $s = sprintf "%-${len}s", $i;
	if( $i == 1 || $i == $r - 3 ) {
		while( length($s) + 10 < $c ) {
			$s .= sprintf "%-10s", length($s);
			$len += 10;
		}
	}
	my $fmt = sprintf "%%%ds\n", $c - length($s);
	$s .= sprintf $fmt, $i;
	print $s;
	$i += 1;
}
draw_horizontal();
