#!/usr/bin/env perl

use strict;
use warnings;

my $c = $ENV{"COLS"};
my $msg = $ARGV[0] // getppid();
sub draw_horizontal {
	my $i = 0;
	while( $i < $c ) {
		printf "%s", ($i % 10) ? ($i % 10) : "|";
		$i += 1;
	}
}
draw_horizontal();
my $i = 1;
while( $i < $ENV{"ROWS"} - 2 ) {
	my $s = sprintf "%-10s", $i;
	if( $i == 1 || $i == $ENV{"ROWS"} - 3 ) {
		while( length($s) + 10 < $c ) {
			$s .= sprintf "%-10s", length($s);
		}
	} else {
		$s .= " " . $msg;
	}
	my $fmt = sprintf "%%%ds\n", $c - length($s);
	$s .= sprintf $fmt, $i;
	print $s;
	$i += 1;
}
draw_horizontal();
