#!/usr/bin/env perl


use strict;
use warnings;
use 5.10.0;
no warnings 'experimental::smartmatch'; # perldoc warnings

my $needle   = 'bar';
my @set     = qw(foo bar baz);

if ($needle ~~ @set) {
	say "$needle is in '@set'";
}
