#!/usr/bin/env perl
use 5.12.0;

sub foo {
	say "first arg is '$_[0]'";
	say "third arg is '$_[2]'";  # no error; just a blank string
	foreach my $x ( @_ ){
		say "foo: ", $x;
	}
}

my $b = sub {
	foreach my $x ( @_ ){
		say "bar: ", $x;
	}
};

foo 'called', 'directly';

my $r = \&foo;
$r->('called', 'thru', '->');
&$r('called', 'with', '&$');
$b->('called', 'via', '->');
