#!/usr/bin/env perl

# emulate sed -i 's/foo/bar/g', but do not break links

# perl -mTie::File -e 'tie @ar, "Tie::File","$ARGV[0]" or die $!; for (@ar) { s/foo/bar/g}' input

use strict;
use warnings;
use Tie::File;

tie my @ar, 'Tie::File', $ARGV[0] or die "$ARGV[0]: $!\n";
s/foo/bar/g foreach(@ar);
