#!/usr/bin/env perl

use 5.12.0;
my $string = "\t[ this is a bra\tcket ]  \t\n foo";

say "string is: '$string'";
print "After applying =~: ";
$string =~ s/^\s*[[][^]]*[]]\s*//;
say "string is changed to '$string'";
