#!/bin/sh

if test -z "$arg"; then
	# filter input by trimming  to a specified width
	perl -nE "chomp; say substr \$_, 0, ${COLUMNS-80} - 1" "$@"
else
	# trim arguments
	perl -E 'say substr "@ARGV", 0, '"${COLUMNS-80}" "$@"
fi

# Overwrite final characters of a string with "..."
perl -E 'my $msg = "this is a string, and the \"n\" is the 15th char";
	$max = 15;
	if (length $msg > $max) {
		substr($msg, $max - 3) = "..."
	}
	$msg eq "this is a st..." or die "Assertion failed";
'

# Print enumerated
# perl -E 'say ((0..9) x 50)'
