#!/bin/sh

if test -z "$arg"; then
	# filter input by trimming  to a specified width
	perl -nE "chomp; say substr \$_, 0, ${COLUMNS-80} - 1" "$@"
else
	# trim arguments
	perl -E 'say substr "@ARGV", 0, '"${COLUMNS-80}" "$@"
fi



# Print enumerated
# perl -E 'say ((0..9) x 50)'
