#!/bin/bash

die() { printf "%s: %s: %s\n" \
	"$(basename $0)" \
	"$(date +"%Y-%m-%d %H:%M:%S%z")" \
	"${*-Failed}"
	exit 1;
} >&2

( die "Test with args" )
echo 'Testing die without arguments...'
( die )
die Terminating
