#!/bin/bash

die() { echo "$(basename $0): $(date +"%Y-%m-%d %H:%M:%S%z"): ${*-Failed}"; exit 1; } >&2
warn() { printf "%s${1:+\n}" "$*"; } >&2
die() { warn "$@"; exit 1; } >&2
die() { printf "%s${1:+\n}" "$*"; exit 1; } >&2

( die "Test with args" )
echo 'Testing die without arguments...'
( die )
die Terminating
