#!/bin/bash


die() { echo "$@"; exit 1; } >&2
exec 9< $0
flock -n 9 || die "Already running: ($(pgrep $(basename $0) | tr \\n \ ))"
flock 9

sh -c 'echo $$:start; cat 0<&9; echo end'
sh -c 'echo $$:start; sleep 500; echo end'

exec 9<&-
wait
