#!/bin/sh

usage() { printf "usage: %s [-c] [-d arg] args ...\n" "$(basename $0)"; }
die() { echo "$@" >&2; exit 1; }

parse_args() {
	while getopts ":cd:h" opt; do
		case $opt in
		c) FLAG_C=1;;
		d) FLAG_D=$OPTARG;;
		h) usage; exit 0;;
		*) die "illegal option -$OPTARG (-h for usage)"
		esac
	done
}

parse_args "$@"
# Reset OPTIND=1 if you call getops again

shift $(($OPTIND-1))
echo FLAG_C=$FLAG_C
echo FLAG_D=$FLAG_D
echo args: "$@"
