#!/bin/bash

foo() {
	declare -n ref=$1
	ref=foo
}

bar=banana
echo $bar
foo bar  # Modifies named variable
echo $bar

foo=foo
bar=bar
declare -n idx
echo $foo $bar $baz
for idx in foo bar baz; do
	idx=new  # Modifies named variable
done
echo $foo $bar $baz
