#!/bin/sh

# Simple example to prepend string to different streams

cmd() {
	echo $1 written to stdout
	echo $2 written to stderr >&2
}

execute() {
	{ "$@" | sed 's/^/stdout: /' 1>&3; } 2>&1 \
	| sed 's/^/stderr: /' >&2
} 3>&1

execute cmd foo "bar baz"
