#!/bin/sh

set -m
chld() {
	while read spec pid status cmd; do
		test "${status#Done}" = "${status}" && continue
		wait $pid
		echo job "$cmd" returned $?
	done <<- EOF
	$(jobs -l)
	EOF
}
trap chld SIGCHLD

./b.sh 3 quz &
./b.sh 2 foo &
./b.sh 1 bar &
wait
