#!/bin/bash

# export and : "special" builtins behave oddly.  In particular, with
# posix compatibility enabled, the following variables retain their value.
# If you run in non-compat mode, bash will not set the variables.

# See http://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html#tag_18_14

a=foo :
b=bar export c=qux

printf "%10s: " "${POSIXLY_CORRECT-non}compat"
printf "\ta=%s\tb=%s\tc=%s\n" "$a" "$b" "$c"

test -z "${POSIXLY_CORRECT+k}" && POSIXLY_CORRECT= bash $0
