#!/bin/sh

# Demonstrate various ways to insert newlines
show() {
	echo arguments:
	i=0
	for x; do printf "$((++i)):\t%s\n" "$x"; done
}

csv() {
	printf "%s" "$1"
	shift
	for x; do printf ",%s" "$x"; done
}
csv2() {
	perl -e "print join ',', qw($*)"
}
show foo bar $( csv \
	this \
	is a \
	comma \
	list \
) and $( csv2 "
	this is
	another
")

# Requires hard tabs
show foo baa $( tr <<- EOF \\n , | sed -e 's/,$//'
	this
	should
	be
	a
	comma
	separated
	list
	EOF
) qux

# Allows leading spaces
show foo baa $( tr <<- EOF -s ' \n' ,, | sed -e 's/^,//' -e 's/,$//'
        this
        should
        be
        a
        comma
        separated
        list
EOF
) qux
