#!/bin/sh
# usage: @NAME@ [-h] required_argument [optional_argument ...]
#
# options:
#   -h         print usage statement

case "$1" in
-h)
	sed -E -e 1d -e "/^#/!q; s/# ?//; s|@NAME@|$(basename $0)|" "$0"
	exit
esac
