#!/bin/sh
# usage: @NAME@ [-h] required_argument [optional_argument ...]
#
# options:
#   -h         print usage statement

case "$1" in
-h)
	sed -nE -e "1d; /^$/q; s|@NAME@|$(basename $0)|; s/# ?//p;" "$0"
	exit
esac
