#!/bin/sh
# usage: @NAME@ [-h] required_operand [operand ...]
#
# options:
#   -h         print usage statement

case "$1" in
-h)
	sed -E -e 1d -e "s|@NAME@|$(basename $0)|" -e '/^#/!q' -e 's/# ?//' $0
	exit
esac
