#!/bin/bash

# Establish a work queue.  Runs 5 commands at a time.

pgid=$(ps -o pgid= $$| tr -d ' ')
trap 'kill $pgid; rm -f $fifo' 0
fifo=$(mktemp)
rm $fifo
mkfifo $fifo
: < $fifo &
exec 4> $fifo
exec 5< $fifo

cmd() {
	count=$((1 + $RANDOM%3))
	printf "%s sleep $count $@  id: $ID\n" "$(date)" >&2
	sleep $count
	echo $?:$ID >&4  # Echo status into fifo
}

run() {
	: $((ID+= 1))
	cmd "$@" &
}

{
run
run
run
run
run
while read -u 5 status; do
	run $status
done
wait
}

